import { Check, KeyRound, Save, ShieldCheck } from "lucide-react"
import { useEffect, useState } from "react"

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/Alert"
import { Badge } from "@/components/ui/Badge"
import { Button } from "@/components/ui/Button"
import { Card, CardContent, CardFooter, CardHeader } from "@/components/ui/Card"
import { Field, FieldGroup, FieldLabel } from "@/components/ui/Field"
import { Input } from "@/components/ui/Input"
import { PageFrame } from "@/components/layout/PageFrame"
import { PageTitle } from "@/components/layout/PageHeading"
import { getApiErrorMessage } from "@/shared/http/api-errors"
import { isRequestAborted, useLatestRequest } from "@/shared/hooks/useLatestRequest"
import { useLocale } from "@/shared/i18n/i18n"
import type { InferenceProvidersResponse, InferenceRoutesResponse } from "@/shared/http/api-types"
import { createInferenceProvider, getInferenceProviders, getInferenceRoutes, updateInferenceProvider, updateInferenceRoutes, verifyInferenceProvider } from "@/settings/inference.api"

export function InferencePage({ onNavigate }: { onNavigate: (path: string) => void }) {
  const { messages } = useLocale(); const copy = messages.inference.ui
  const [data, setData] = useState<InferenceProvidersResponse | null>(null); const [routes, setRoutes] = useState<InferenceRoutesResponse | null>(null)
  const [name, setName] = useState(""); const [baseUrl, setBaseUrl] = useState("https://api.openai.com/v1"); const [key, setKey] = useState(""); const [models, setModels] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  const { begin } = useLatestRequest()
  useEffect(() => { const request = begin(); void Promise.all([getInferenceProviders(request.signal), getInferenceRoutes(request.signal)]).then(([providers, routeResponse]) => { if (!request.isCurrent()) return; setData(providers); setRoutes(routeResponse); setName(providers.providers[0]?.name ?? ""); setBaseUrl(providers.providers[0]?.baseUrl ?? "https://api.openai.com/v1"); setModels(Object.fromEntries(routeResponse.routes.map((route) => [route.capabilityCode, route.modelName ?? ""]))) }).catch((loadError) => { if (request.isCurrent() && !isRequestAborted(loadError, request.signal)) setError(getApiErrorMessage(loadError, copy.error, messages.common.ui.errors)) }) }, [begin, copy.error, messages.common.ui.errors])
  const provider = data?.providers[0]
  async function saveProvider() { setBusy(true); setError(null); setNotice(null); try { const result = provider ? await updateInferenceProvider(provider.id, { name: name.trim(), baseUrl: baseUrl.trim(), apiKey: { action: key.trim() ? "replace" : "keep", value: key.trim() || null }, expectedRevision: provider.revision }) : await createInferenceProvider({ name: name.trim(), baseUrl: baseUrl.trim(), apiKey: { action: key.trim() ? "replace" : "clear", value: key.trim() || null } }); setData((current) => current ? { ...current, providers: [result] } : current); setKey(""); setNotice(copy.saved) } catch (saveError) { setError(getApiErrorMessage(saveError, copy.error, messages.common.ui.errors)) } finally { setBusy(false) } }
  async function saveModels() { if (!routes || !provider) return; setBusy(true); setError(null); setNotice(null); try { const result = await updateInferenceRoutes({ routes: routes.routes.map((route) => ({ capabilityCode: route.capabilityCode, providerId: models[route.capabilityCode]?.trim() ? provider.id : null, modelName: models[route.capabilityCode]?.trim() || null, expectedRevision: route.revision })) }); setRoutes(result); setNotice(copy.saved) } catch (saveError) { setError(getApiErrorMessage(saveError, copy.error, messages.common.ui.errors)) } finally { setBusy(false) } }
  async function verify() { if (!provider) return; setBusy(true); try { const result = await verifyInferenceProvider(provider.id, { expectedRevision: provider.revision }); setData((current) => current ? { ...current, providers: [result.provider] } : current); setNotice(copy.verified) } catch (verifyError) { setError(getApiErrorMessage(verifyError, copy.error, messages.common.ui.errors)) } finally { setBusy(false) } }
  const statusLabel = (code: string) => code === "configured-unverified" ? copy.configuredUnverified : code === "recently-verified" ? copy.recentlyVerified : code === "currently-unavailable" ? copy.currentlyUnavailable : copy.unconfigured
  return <PageFrame currentPath="/settings" onNavigate={onNavigate} contentClassName="settings-subpage-wrap"><PageTitle eyebrow={copy.eyebrow} title={copy.title} description={copy.description} />{error && <Alert variant="destructive"><AlertTitle>{messages.common.ui.states.applicationError.title}</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}{notice && <Alert><Check size={16} aria-hidden="true" /><AlertDescription>{notice}</AlertDescription></Alert>}<Card className="settings-subpage-card"><CardHeader><h2>{copy.providerTitle}</h2></CardHeader><CardContent><FieldGroup className="settings-provider-fields"><Field><FieldLabel>{copy.nameLabel}</FieldLabel><Input value={name} placeholder={copy.namePlaceholder} onChange={(event) => setName(event.target.value)} /></Field><Field><FieldLabel>{copy.baseUrlLabel}</FieldLabel><Input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} /></Field><Field><FieldLabel><KeyRound size={14} aria-hidden="true" />{copy.keyLabel}</FieldLabel><Input type="password" value={key} placeholder={provider ? provider.secretState.stateCode : copy.keyPlaceholder} onChange={(event) => setKey(event.target.value)} autoComplete="new-password" /></Field></FieldGroup></CardContent><CardFooter><Button onClick={() => void saveProvider()} disabled={busy}><Save data-icon="inline-start" />{copy.save}</Button>{provider && <Button variant="outline" onClick={() => void verify()} disabled={busy}><ShieldCheck data-icon="inline-start" />{copy.verify}</Button>}</CardFooter></Card><Card className="settings-subpage-card"><CardHeader><h2>{copy.routesTitle}</h2></CardHeader><CardContent className="settings-route-list">{routes?.routes.map((route) => <div className="settings-route-row" key={route.capabilityCode}><div><strong>{route.capabilityCode === "chat" ? copy.chat : copy.embedding}</strong><Badge variant={route.runtimeStatusCode === "unconfigured" ? "outline" : "accent"}>{statusLabel(route.runtimeStatusCode)}</Badge></div><Input value={models[route.capabilityCode] ?? ""} placeholder={copy.modelPlaceholder} onChange={(event) => setModels((current) => ({ ...current, [route.capabilityCode]: event.target.value }))} /></div>)}</CardContent><CardFooter><Button onClick={() => void saveModels()} disabled={busy || !provider || !routes}><Save data-icon="inline-start" />{copy.saveRoutes}</Button></CardFooter></Card></PageFrame>
}
