import { Check, KeyRound, Save, ShieldCheck } from "lucide-react"
import { useCallback, useEffect, useMemo, useState } from "react"

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/Alert"
import { Badge } from "@/components/ui/Badge"
import { Button } from "@/components/ui/Button"
import { Card, CardContent, CardFooter, CardHeader } from "@/components/ui/Card"
import { Field, FieldGroup, FieldLabel } from "@/components/ui/Field"
import { Input } from "@/components/ui/Input"
import { PageFrame } from "@/components/layout/PageFrame"
import { PageTitle } from "@/components/layout/PageHeading"
import { getApiErrorMessage } from "@/shared/http/api-errors"
import { isRequestAborted, useLatestRequest } from "@/shared/hooks/useLatestRequest"
import { useLocale } from "@/shared/i18n/i18n"
import type { StockDataProvidersResponse, StockDataRoutesResponse } from "@/shared/http/api-types"
import { createStockDataProvider, getStockDataProviders, getStockDataRoutes, updateStockDataProvider, updateStockDataRoutes, verifyStockDataProvider } from "@/settings/stock-data-providers.api"

export function StockDataProvidersPage({ onNavigate }: { onNavigate: (path: string) => void }) {
  const { messages } = useLocale(); const copy = messages.stockDataProviders.ui
  const [data, setData] = useState<StockDataProvidersResponse | null>(null); const [routes, setRoutes] = useState<StockDataRoutesResponse | null>(null)
  const [name, setName] = useState("FTShare"); const [key, setKey] = useState(""); const [selected, setSelected] = useState<Record<string, string | null>>({}); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [error, setError] = useState<string | null>(null)
  const { begin } = useLatestRequest()
  const load = useCallback(() => { const request = begin(); setError(null); void Promise.all([getStockDataProviders(request.signal), getStockDataRoutes(request.signal)]).then(([providers, routeResponse]) => { if (!request.isCurrent()) return; setData(providers); setRoutes(routeResponse); setSelected(Object.fromEntries(routeResponse.routes.map((route) => [route.capabilityCode, route.providerId]))) }).catch((loadError) => { if (request.isCurrent() && !isRequestAborted(loadError, request.signal)) setError(getApiErrorMessage(loadError, copy.error, messages.common.ui.errors)) }) }, [begin, copy.error, messages.common.ui.errors])
  useEffect(() => { const timeoutId = window.setTimeout(load, 0); return () => window.clearTimeout(timeoutId) }, [load])
  const definition = useMemo(() => data?.definitions.find((item) => item.providerKindCode === "ftshare"), [data])
  const provider = data?.providers[0]
  async function saveProvider() { if (!definition || !name.trim()) return; setBusy(true); setError(null); setNotice(null); try { const result = provider ? await updateStockDataProvider(provider.id, { name: name.trim(), credentials: { action: key.trim() ? "replace" : "keep", value: key.trim() || null }, expectedRevision: provider.revision }) : await createStockDataProvider({ providerDefinitionId: definition.id, name: name.trim(), credentials: { action: key.trim() ? "replace" : "clear", value: key.trim() || null } }); setData((current) => current ? { ...current, providers: [result] } : current); setKey(""); setNotice(copy.saved) } catch (saveError) { setError(getApiErrorMessage(saveError, copy.error, messages.common.ui.errors)) } finally { setBusy(false) } }
  async function saveRoutes() { if (!routes) return; setBusy(true); setError(null); setNotice(null); try { const result = await updateStockDataRoutes({ routes: routes.routes.map((route) => ({ capabilityCode: route.capabilityCode, providerId: selected[route.capabilityCode] ?? null, expectedRevision: route.revision })) }); setRoutes(result); setNotice(copy.saved) } catch (saveError) { setError(getApiErrorMessage(saveError, copy.error, messages.common.ui.errors)) } finally { setBusy(false) } }
  async function verify() { if (!provider) return; setBusy(true); try { const result = await verifyStockDataProvider(provider.id, { expectedRevision: provider.revision }); setData((current) => current ? { ...current, providers: [result.provider] } : current); setNotice(copy.verified) } catch (verifyError) { setError(getApiErrorMessage(verifyError, copy.error, messages.common.ui.errors)) } finally { setBusy(false) } }
  const statusLabel = (code: string) => code === "configured-unverified" ? copy.configuredUnverified : code === "recently-verified" ? copy.recentlyVerified : code === "currently-unavailable" ? copy.currentlyUnavailable : copy.unconfigured
  return <PageFrame currentPath="/settings" onNavigate={onNavigate} contentClassName="settings-subpage-wrap"><PageTitle eyebrow={copy.eyebrow} title={copy.title} description={copy.description} />{error && <Alert variant="destructive"><AlertTitle>{messages.common.ui.states.applicationError.title}</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}{notice && <Alert><Check size={16} aria-hidden="true" /><AlertDescription>{notice}</AlertDescription></Alert>}<Card className="settings-subpage-card"><CardHeader><h2>{copy.providerTitle}</h2></CardHeader><CardContent><FieldGroup className="settings-provider-fields"><Field><FieldLabel>{copy.nameLabel}</FieldLabel><Input value={name} placeholder={copy.namePlaceholder} onChange={(event) => setName(event.target.value)} /></Field><Field><FieldLabel><KeyRound size={14} aria-hidden="true" />{copy.keyLabel}</FieldLabel><Input type="password" value={key} placeholder={provider ? provider.secretState.stateCode : copy.keyPlaceholder} onChange={(event) => setKey(event.target.value)} autoComplete="new-password" /></Field></FieldGroup></CardContent><CardFooter><Button onClick={() => void saveProvider()} disabled={busy || !definition}><Save data-icon="inline-start" />{copy.save}</Button>{provider && <Button variant="outline" onClick={() => void verify()} disabled={busy}><ShieldCheck data-icon="inline-start" />{copy.verify}</Button>}</CardFooter></Card><Card className="settings-subpage-card"><CardHeader><h2>{copy.routesTitle}</h2><p>{copy.routeHint}</p></CardHeader><CardContent className="settings-route-list">{routes?.routes.map((route) => <div className="settings-route-row" key={route.capabilityCode}><span>{messages.settings.ui.overview.capabilities[route.capabilityCode as keyof typeof messages.settings.ui.overview.capabilities] ?? route.capabilityCode}</span><Badge variant={route.runtimeStatusCode === "unconfigured" ? "outline" : "accent"}>{statusLabel(route.runtimeStatusCode)}</Badge><select value={selected[route.capabilityCode] ?? ""} onChange={(event) => setSelected((current) => ({ ...current, [route.capabilityCode]: event.target.value || null }))}><option value="">{copy.unconfigured}</option>{data?.providers.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div>)}</CardContent><CardFooter><Button onClick={() => void saveRoutes()} disabled={busy || !routes}><Save data-icon="inline-start" />{copy.save}</Button></CardFooter></Card></PageFrame>
}
