// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portwise.Infrastructure;

#nullable disable

namespace Portwise.Infrastructure.Migrations
{
    [DbContext(typeof(PortwiseDbContext))]
    [Migration("20260911224452_AddConfigurationFoundation")]
    partial class AddConfigurationFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portwise.Domain.Models.ApplicationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("theme_code");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_application_preferences");

                    b.ToTable("application_preferences", "public", t =>
                        {
                            t.HasCheckConstraint("ck_application_preferences_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Portwise.Domain.Models.CashLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cash_ledger_entry_id");

                    b.Property<decimal>("CashAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("cash_amount");

                    b.Property<string>("CashDirectionCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cash_direction_code");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type_code");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid?>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_record_id");

                    b.HasKey("Id")
                        .HasName("pk_cash_ledger_entries");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_cash_ledger_entries_security_id");

                    b.HasIndex("PortfolioId", "SourceRecordId")
                        .IsUnique()
                        .HasDatabaseName("uq_cash_ledger_entries_portfolio_source_record")
                        .HasFilter("source_record_id IS NOT NULL");

                    b.ToTable("cash_ledger_entries", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.DividendEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dividend_event_id");

                    b.Property<DateOnly?>("AnnouncementDate")
                        .HasColumnType("date")
                        .HasColumnName("announcement_date");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("DataQualityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_quality_code");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_source");

                    b.Property<decimal>("DividendPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("dividend_per_share");

                    b.Property<string>("DividendStatusCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dividend_status_code");

                    b.Property<string>("DividendTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dividend_type_code");

                    b.Property<DateOnly?>("ExDividendDate")
                        .HasColumnType("date")
                        .HasColumnName("ex_dividend_date");

                    b.Property<bool>("IsSpecialDividend")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special_dividend");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_record_id");

                    b.HasKey("Id")
                        .HasName("pk_dividend_events");

                    b.HasIndex("SecurityId", "SourceRecordId")
                        .IsUnique()
                        .HasDatabaseName("uq_dividend_events_security_source_record");

                    b.ToTable("dividend_events", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.FinancialSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("financial_snapshot_id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateOnly>("DataAsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("data_as_of_date");

                    b.Property<string>("DataQualityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_quality_code");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_source");

                    b.Property<decimal?>("DividendPayoutRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("dividend_payout_ratio");

                    b.Property<decimal?>("EarningsPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("earnings_per_share");

                    b.Property<decimal?>("PriceToBookRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("price_to_book_ratio");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<decimal?>("ReturnOnEquity")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("return_on_equity");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_record_id");

                    b.Property<decimal?>("ThreeYearAverageDividendPayoutRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("three_year_average_dividend_payout_ratio");

                    b.HasKey("Id")
                        .HasName("pk_financial_snapshots");

                    b.HasIndex("SecurityId", "DataAsOfDate")
                        .IsUnique()
                        .HasDatabaseName("uq_financial_snapshots_security_data_as_of_date");

                    b.ToTable("financial_snapshots", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.FtShareProviderSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExchangeCodeArgumentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("exchange_code_argument_name");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_retry_count");

                    b.Property<string>("McpEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mcp_endpoint");

                    b.Property<Guid>("ProviderDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_definition_id");

                    b.Property<int>("RequestTimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("request_timeout_seconds");

                    b.Property<int>("RetryDelayMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("retry_delay_milliseconds");

                    b.Property<string>("SecurityCodeArgumentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("security_code_argument_name");

                    b.Property<string>("StockDividendEventsToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stock_dividend_events_tool_name");

                    b.Property<string>("StockFinancialSnapshotsToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stock_financial_snapshots_tool_name");

                    b.Property<string>("StockMarketDataToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stock_market_data_tool_name");

                    b.Property<string>("StockProfileToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stock_profile_tool_name");

                    b.HasKey("Id")
                        .HasName("pk_ftshare_provider_settings");

                    b.HasIndex("ProviderDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("uq_ftshare_provider_settings_provider_definition_id");

                    b.ToTable("ftshare_provider_settings", "public", t =>
                        {
                            t.HasCheckConstraint("ck_ftshare_provider_settings_max_retry_count", "max_retry_count >= 0");

                            t.HasCheckConstraint("ck_ftshare_provider_settings_request_timeout_seconds", "request_timeout_seconds > 0");

                            t.HasCheckConstraint("ck_ftshare_provider_settings_retry_delay_milliseconds", "retry_delay_milliseconds >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a0929e-0a1d-721b-9e74-ce8d31633069"),
                            ExchangeCodeArgumentName = "exchange_code",
                            MaxRetryCount = 2,
                            McpEndpoint = "https://market.ft.tech/gateway/mcp",
                            ProviderDefinitionId = new Guid("01a0929e-0a1c-7ffa-86f5-e6626219e9d2"),
                            RequestTimeoutSeconds = 30,
                            RetryDelayMilliseconds = 250,
                            SecurityCodeArgumentName = "security_code",
                            StockDividendEventsToolName = "get_stock_dividend_events",
                            StockFinancialSnapshotsToolName = "get_stock_financial_snapshots",
                            StockMarketDataToolName = "get_stock_market_data",
                            StockProfileToolName = "get_stock_profile"
                        });
                });

            modelBuilder.Entity("Portwise.Domain.Models.InferenceProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastVerificationErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_verification_error_code");

                    b.Property<DateTimeOffset?>("LastVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("ProtectedApiKey")
                        .HasColumnType("text")
                        .HasColumnName("protected_api_key");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider_type");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VerificationState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("verification_state");

                    b.HasKey("Id")
                        .HasName("pk_inference_providers");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("uq_inference_providers_normalized_name");

                    b.ToTable("inference_providers", "public", t =>
                        {
                            t.HasCheckConstraint("ck_inference_providers_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Portwise.Domain.Models.InferenceRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("capability");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_name");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_inference_routes");

                    b.HasIndex("Capability")
                        .IsUnique()
                        .HasDatabaseName("uq_inference_routes_capability");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_inference_routes_provider_id");

                    b.ToTable("inference_routes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_inference_routes_binding", "(provider_id IS NULL AND model_name IS NULL) OR (provider_id IS NOT NULL AND model_name IS NOT NULL)");

                            t.HasCheckConstraint("ck_inference_routes_revision", "revision > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a0929e-0a22-7eec-bdf8-94c2db32b317"),
                            Capability = "chat",
                            Revision = 1L,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("01a0929e-0a23-7c2e-9948-e2028030f99a"),
                            Capability = "embedding",
                            Revision = 1L,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Portwise.Domain.Models.InitializationState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_initialization_states");

                    b.ToTable("initialization_states", "public", t =>
                        {
                            t.HasCheckConstraint("ck_initialization_states_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Portwise.Domain.Models.ModelParameterSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("model_parameter_set_id");

                    b.Property<decimal>("AccumulateBudgetRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("accumulate_budget_ratio");

                    b.Property<decimal>("AccumulationYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("accumulation_yield_threshold");

                    b.Property<decimal>("AggressiveTrimRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("aggressive_trim_ratio");

                    b.Property<decimal>("AggressiveTrimYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("aggressive_trim_yield_threshold");

                    b.Property<decimal>("CashReserveRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("cash_reserve_ratio");

                    b.Property<DateOnly>("EffectiveFromDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_from_date");

                    b.Property<decimal>("MaxPeriodBudgetAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("max_period_budget_amount");

                    b.Property<decimal>("MaxSectorWeight")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("max_sector_weight");

                    b.Property<decimal>("MaxSecurityWeight")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("max_security_weight");

                    b.Property<decimal>("MaxSingleTradeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("max_single_trade_amount");

                    b.Property<decimal>("MinimumTransactionFeeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("minimum_transaction_fee_amount");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("model_version");

                    b.Property<decimal>("PartialTrimRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("partial_trim_ratio");

                    b.Property<decimal>("PartialTrimYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("partial_trim_yield_threshold");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<decimal>("StrongBuyBudgetRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("strong_buy_budget_ratio");

                    b.Property<decimal>("StrongBuyYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("strong_buy_yield_threshold");

                    b.Property<int>("TradingLotSize")
                        .HasColumnType("integer")
                        .HasColumnName("trading_lot_size");

                    b.Property<decimal>("TransactionFeeRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("transaction_fee_ratio");

                    b.HasKey("Id")
                        .HasName("pk_model_parameter_sets");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_model_parameter_sets_security_id");

                    b.HasIndex("PortfolioId", "SecurityId", "EffectiveFromDate")
                        .IsUnique()
                        .HasDatabaseName("uq_model_parameter_sets_portfolio_security_effective_from");

                    b.ToTable("model_parameter_sets", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("portfolio_name");

                    b.Property<string>("PortfolioScope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("default")
                        .HasColumnName("portfolio_scope");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("PortfolioScope")
                        .IsUnique()
                        .HasDatabaseName("uq_portfolios_portfolio_scope");

                    b.ToTable("portfolios", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PortfolioPosition", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<decimal>("AverageCostPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("average_cost_per_share");

                    b.Property<int>("CoreShares")
                        .HasColumnType("integer")
                        .HasColumnName("core_shares");

                    b.Property<int>("HeldShares")
                        .HasColumnType("integer")
                        .HasColumnName("held_shares");

                    b.Property<int>("TargetShares")
                        .HasColumnType("integer")
                        .HasColumnName("target_shares");

                    b.HasKey("PortfolioId", "SecurityId")
                        .HasName("pk_portfolio_positions");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_portfolio_positions_security_id");

                    b.ToTable("portfolio_positions", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PortfolioTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_trade_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("PricePerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("price_per_share");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<int>("ShareQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("share_quantity");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_record_id");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.Property<string>("TradeDirectionCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trade_direction_code");

                    b.Property<decimal>("TransactionFeeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("transaction_fee_amount");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_trades");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_portfolio_trades_security_id");

                    b.HasIndex("PortfolioId", "SourceRecordId")
                        .IsUnique()
                        .HasDatabaseName("uq_portfolio_trades_portfolio_source_record");

                    b.HasIndex("PortfolioId", "TradeDate")
                        .HasDatabaseName("ix_portfolio_trades_portfolio_trade_date");

                    b.ToTable("portfolio_trades", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PriceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("price_observation_id");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("close_price");

                    b.Property<string>("DataQualityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_quality_code");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_source");

                    b.Property<DateTimeOffset>("PriceObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_observed_at");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_record_id");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date")
                        .HasColumnName("trading_date");

                    b.HasKey("Id")
                        .HasName("pk_price_observations");

                    b.HasIndex("SecurityId", "TradingDate")
                        .IsUnique()
                        .HasDatabaseName("uq_price_observations_security_trading_date");

                    b.ToTable("price_observations", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.RecommendationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_snapshot_id");

                    b.Property<decimal?>("ClosePrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("close_price");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateOnly?>("DataAsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("data_as_of_date");

                    b.Property<string>("DividendModeCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dividend_mode_code");

                    b.Property<string>("DividendReliabilityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dividend_reliability_code");

                    b.Property<decimal?>("DividendYield")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("dividend_yield");

                    b.Property<decimal>("EstimatedTransactionFeeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("estimated_transaction_fee_amount");

                    b.Property<decimal?>("ModelDividendPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("model_dividend_per_share");

                    b.Property<Guid?>("ModelParameterSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_parameter_set_id");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<string>("ModelStatusCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("model_status_code");

                    b.Property<string>("ObservedPriceZoneCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("observed_price_zone_code");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("PriceZoneCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("price_zone_code");

                    b.Property<bool>("PriceZoneConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("price_zone_confirmed");

                    b.Property<string>("RecommendationCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recommendation_code");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<int>("SuggestedBuyShares")
                        .HasColumnType("integer")
                        .HasColumnName("suggested_buy_shares");

                    b.Property<int>("SuggestedSellShares")
                        .HasColumnType("integer")
                        .HasColumnName("suggested_sell_shares");

                    b.Property<decimal>("SuggestedTradeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("suggested_trade_amount");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_snapshots");

                    b.HasIndex("ModelParameterSetId")
                        .HasDatabaseName("ix_recommendation_snapshots_model_parameter_set_id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_recommendation_snapshots_portfolio_id");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_recommendation_snapshots_security_id");

                    b.HasIndex("ModelRunId", "PortfolioId", "SecurityId")
                        .IsUnique()
                        .HasDatabaseName("uq_recommendation_snapshots_model_run_portfolio_security");

                    b.ToTable("recommendation_snapshots", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.Security", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("exchange_code");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("market_code");

                    b.Property<string>("SectorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector_code");

                    b.Property<string>("SecurityCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("security_code");

                    b.Property<string>("SecurityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("security_name");

                    b.HasKey("Id")
                        .HasName("pk_securities");

                    b.HasIndex("ExchangeCode", "SecurityCode")
                        .IsUnique()
                        .HasDatabaseName("uq_securities_exchange_security_code");

                    b.ToTable("securities", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.StockDataProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("LastVerificationErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_verification_error_code");

                    b.Property<DateTimeOffset?>("LastVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_verified_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProtectedCredentials")
                        .HasColumnType("text")
                        .HasColumnName("protected_credentials");

                    b.Property<Guid>("ProviderDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_definition_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VerificationState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("verification_state");

                    b.HasKey("Id")
                        .HasName("pk_stock_data_providers");

                    b.HasIndex("ProviderDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("uq_stock_data_providers_provider_definition_id");

                    b.ToTable("stock_data_providers", "public", t =>
                        {
                            t.HasCheckConstraint("ck_stock_data_providers_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("Portwise.Domain.Models.StockDataProviderDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider_kind");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_stock_data_provider_definitions");

                    b.HasIndex("ProviderKind")
                        .IsUnique()
                        .HasDatabaseName("uq_stock_data_provider_definitions_provider_kind");

                    b.ToTable("stock_data_provider_definitions", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a0929e-0a1c-7ffa-86f5-e6626219e9d2"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "FTShare",
                            IsEnabled = true,
                            ProviderKind = "ftshare",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Portwise.Domain.Models.StockDataRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("capability");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_stock_data_routes");

                    b.HasIndex("Capability")
                        .IsUnique()
                        .HasDatabaseName("uq_stock_data_routes_capability");

                    b.HasIndex("ProviderId")
                        .HasDatabaseName("ix_stock_data_routes_provider_id");

                    b.ToTable("stock_data_routes", "public", t =>
                        {
                            t.HasCheckConstraint("ck_stock_data_routes_revision", "revision > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("01a0929e-0a1e-79eb-b895-61b60ce05be8"),
                            Capability = "profile",
                            Revision = 1L,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("01a0929e-0a1f-7fa1-9e4c-bc69e95fa39e"),
                            Capability = "market",
                            Revision = 1L,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("01a0929e-0a20-7e10-a15e-f1b39354fb0b"),
                            Capability = "dividend",
                            Revision = 1L,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("01a0929e-0a21-74d9-a33f-e04567185f75"),
                            Capability = "financial",
                            Revision = 1L,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Portwise.Domain.Models.CashLedgerEntry", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cash_ledger_entries_portfolios_portfolio_id");

                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cash_ledger_entries_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.DividendEvent", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dividend_events_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.FinancialSnapshot", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_snapshots_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.FtShareProviderSettings", b =>
                {
                    b.HasOne("Portwise.Domain.Models.StockDataProviderDefinition", null)
                        .WithOne()
                        .HasForeignKey("Portwise.Domain.Models.FtShareProviderSettings", "ProviderDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ftshare_settings_provider_definitions_definition_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.InferenceRoute", b =>
                {
                    b.HasOne("Portwise.Domain.Models.InferenceProvider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inference_routes_inference_providers_provider_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.ModelParameterSet", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_parameter_sets_portfolios_portfolio_id");

                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_model_parameter_sets_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PortfolioPosition", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_positions_portfolios_portfolio_id");

                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_positions_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PortfolioTrade", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_trades_portfolios_portfolio_id");

                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_trades_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PriceObservation", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_price_observations_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.RecommendationSnapshot", b =>
                {
                    b.HasOne("Portwise.Domain.Models.ModelParameterSet", null)
                        .WithMany()
                        .HasForeignKey("ModelParameterSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recommendation_snapshots_model_parameter_set_id");

                    b.HasOne("Portwise.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_snapshots_portfolios_portfolio_id");

                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_snapshots_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.StockDataProvider", b =>
                {
                    b.HasOne("Portwise.Domain.Models.StockDataProviderDefinition", null)
                        .WithOne()
                        .HasForeignKey("Portwise.Domain.Models.StockDataProvider", "ProviderDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_providers_provider_definitions_definition_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.StockDataRoute", b =>
                {
                    b.HasOne("Portwise.Domain.Models.StockDataProvider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_data_routes_stock_data_providers_provider_id");
                });
#pragma warning restore 612, 618
        }
    }
}
