// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portwise.Infrastructure;

#nullable disable

namespace Portwise.Infrastructure.Migrations
{
    [DbContext(typeof(PortwiseDbContext))]
    partial class PortwiseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Portwise.Domain.Models.CashLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("cash_ledger_entry_id");

                    b.Property<decimal>("CashAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("cash_amount");

                    b.Property<string>("CashDirectionCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cash_direction_code");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("entry_type_code");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid?>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_record_id");

                    b.HasKey("Id")
                        .HasName("pk_cash_ledger_entries");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_cash_ledger_entries_security_id");

                    b.HasIndex("PortfolioId", "SourceRecordId")
                        .IsUnique()
                        .HasDatabaseName("uq_cash_ledger_entries_portfolio_source_record")
                        .HasFilter("source_record_id IS NOT NULL");

                    b.ToTable("cash_ledger_entries", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.DividendEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dividend_event_id");

                    b.Property<DateOnly?>("AnnouncementDate")
                        .HasColumnType("date")
                        .HasColumnName("announcement_date");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<string>("DataQualityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_quality_code");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_source");

                    b.Property<decimal>("DividendPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("dividend_per_share");

                    b.Property<string>("DividendStatusCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dividend_status_code");

                    b.Property<string>("DividendTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dividend_type_code");

                    b.Property<DateOnly?>("ExDividendDate")
                        .HasColumnType("date")
                        .HasColumnName("ex_dividend_date");

                    b.Property<bool>("IsSpecialDividend")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special_dividend");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_record_id");

                    b.HasKey("Id")
                        .HasName("pk_dividend_events");

                    b.HasIndex("SecurityId", "SourceRecordId")
                        .IsUnique()
                        .HasDatabaseName("uq_dividend_events_security_source_record");

                    b.ToTable("dividend_events", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.FinancialSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("financial_snapshot_id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<DateOnly>("DataAsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("data_as_of_date");

                    b.Property<string>("DataQualityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_quality_code");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_source");

                    b.Property<decimal?>("DividendPayoutRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("dividend_payout_ratio");

                    b.Property<decimal?>("EarningsPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("earnings_per_share");

                    b.Property<decimal?>("PriceToBookRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("price_to_book_ratio");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<decimal?>("ReturnOnEquity")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("return_on_equity");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_record_id");

                    b.Property<decimal?>("ThreeYearAverageDividendPayoutRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("three_year_average_dividend_payout_ratio");

                    b.HasKey("Id")
                        .HasName("pk_financial_snapshots");

                    b.HasIndex("SecurityId", "DataAsOfDate")
                        .IsUnique()
                        .HasDatabaseName("uq_financial_snapshots_security_data_as_of_date");

                    b.ToTable("financial_snapshots", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.ModelParameterSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("model_parameter_set_id");

                    b.Property<decimal>("AccumulateBudgetRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("accumulate_budget_ratio");

                    b.Property<decimal>("AccumulationYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("accumulation_yield_threshold");

                    b.Property<decimal>("AggressiveTrimRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("aggressive_trim_ratio");

                    b.Property<decimal>("AggressiveTrimYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("aggressive_trim_yield_threshold");

                    b.Property<decimal>("CashReserveRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("cash_reserve_ratio");

                    b.Property<DateOnly>("EffectiveFromDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_from_date");

                    b.Property<decimal>("MaxPeriodBudgetAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("max_period_budget_amount");

                    b.Property<decimal>("MaxSectorWeight")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("max_sector_weight");

                    b.Property<decimal>("MaxSecurityWeight")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("max_security_weight");

                    b.Property<decimal>("MaxSingleTradeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("max_single_trade_amount");

                    b.Property<decimal>("MinimumTransactionFeeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("minimum_transaction_fee_amount");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("model_version");

                    b.Property<decimal>("PartialTrimRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("partial_trim_ratio");

                    b.Property<decimal>("PartialTrimYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("partial_trim_yield_threshold");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<decimal>("StrongBuyBudgetRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("strong_buy_budget_ratio");

                    b.Property<decimal>("StrongBuyYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("strong_buy_yield_threshold");

                    b.Property<int>("TradingLotSize")
                        .HasColumnType("integer")
                        .HasColumnName("trading_lot_size");

                    b.Property<decimal>("TransactionFeeRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("transaction_fee_ratio");

                    b.HasKey("Id")
                        .HasName("pk_model_parameter_sets");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_model_parameter_sets_security_id");

                    b.HasIndex("PortfolioId", "SecurityId", "EffectiveFromDate")
                        .IsUnique()
                        .HasDatabaseName("uq_model_parameter_sets_portfolio_security_effective_from");

                    b.ToTable("model_parameter_sets", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("portfolio_name");

                    b.Property<string>("PortfolioScope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("default")
                        .HasColumnName("portfolio_scope");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("PortfolioScope")
                        .IsUnique()
                        .HasDatabaseName("uq_portfolios_portfolio_scope");

                    b.ToTable("portfolios", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PortfolioPosition", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<decimal>("AverageCostPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("average_cost_per_share");

                    b.Property<int>("CoreShares")
                        .HasColumnType("integer")
                        .HasColumnName("core_shares");

                    b.Property<int>("HeldShares")
                        .HasColumnType("integer")
                        .HasColumnName("held_shares");

                    b.Property<int>("TargetShares")
                        .HasColumnType("integer")
                        .HasColumnName("target_shares");

                    b.HasKey("PortfolioId", "SecurityId")
                        .HasName("pk_portfolio_positions");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_portfolio_positions_security_id");

                    b.ToTable("portfolio_positions", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PortfolioTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_trade_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("PricePerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("price_per_share");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<int>("ShareQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("share_quantity");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_record_id");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("date")
                        .HasColumnName("trade_date");

                    b.Property<string>("TradeDirectionCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trade_direction_code");

                    b.Property<decimal>("TransactionFeeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("transaction_fee_amount");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_trades");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_portfolio_trades_security_id");

                    b.HasIndex("PortfolioId", "SourceRecordId")
                        .IsUnique()
                        .HasDatabaseName("uq_portfolio_trades_portfolio_source_record");

                    b.HasIndex("PortfolioId", "TradeDate")
                        .HasDatabaseName("ix_portfolio_trades_portfolio_trade_date");

                    b.ToTable("portfolio_trades", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PriceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("price_observation_id");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("close_price");

                    b.Property<string>("DataQualityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("data_quality_code");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_source");

                    b.Property<DateTimeOffset>("PriceObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price_observed_at");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_record_id");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("date")
                        .HasColumnName("trading_date");

                    b.HasKey("Id")
                        .HasName("pk_price_observations");

                    b.HasIndex("SecurityId", "TradingDate")
                        .IsUnique()
                        .HasDatabaseName("uq_price_observations_security_trading_date");

                    b.ToTable("price_observations", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.RecommendationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_snapshot_id");

                    b.Property<decimal?>("ClosePrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("close_price");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateOnly?>("DataAsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("data_as_of_date");

                    b.Property<string>("DividendModeCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dividend_mode_code");

                    b.Property<string>("DividendReliabilityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dividend_reliability_code");

                    b.Property<decimal?>("DividendYield")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("dividend_yield");

                    b.Property<decimal>("EstimatedTransactionFeeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("estimated_transaction_fee_amount");

                    b.Property<decimal?>("ModelDividendPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("model_dividend_per_share");

                    b.Property<Guid?>("ModelParameterSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_parameter_set_id");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<string>("ModelStatusCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("model_status_code");

                    b.Property<string>("ObservedPriceZoneCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("observed_price_zone_code");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("PriceZoneCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("price_zone_code");

                    b.Property<bool>("PriceZoneConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("price_zone_confirmed");

                    b.Property<string>("RecommendationCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("recommendation_code");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<int>("SuggestedBuyShares")
                        .HasColumnType("integer")
                        .HasColumnName("suggested_buy_shares");

                    b.Property<int>("SuggestedSellShares")
                        .HasColumnType("integer")
                        .HasColumnName("suggested_sell_shares");

                    b.Property<decimal>("SuggestedTradeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("numeric(20,8)")
                        .HasColumnName("suggested_trade_amount");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_snapshots");

                    b.HasIndex("ModelParameterSetId")
                        .HasDatabaseName("ix_recommendation_snapshots_model_parameter_set_id");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("ix_recommendation_snapshots_portfolio_id");

                    b.HasIndex("SecurityId")
                        .HasDatabaseName("ix_recommendation_snapshots_security_id");

                    b.HasIndex("ModelRunId", "PortfolioId", "SecurityId")
                        .IsUnique()
                        .HasDatabaseName("uq_recommendation_snapshots_model_run_portfolio_security");

                    b.ToTable("recommendation_snapshots", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.Security", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("security_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("exchange_code");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("market_code");

                    b.Property<string>("SectorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector_code");

                    b.Property<string>("SecurityCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("security_code");

                    b.Property<string>("SecurityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("security_name");

                    b.HasKey("Id")
                        .HasName("pk_securities");

                    b.HasIndex("ExchangeCode", "SecurityCode")
                        .IsUnique()
                        .HasDatabaseName("uq_securities_exchange_security_code");

                    b.ToTable("securities", "public");
                });

            modelBuilder.Entity("Portwise.Domain.Models.CashLedgerEntry", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cash_ledger_entries_portfolios_portfolio_id");

                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cash_ledger_entries_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.DividendEvent", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_dividend_events_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.FinancialSnapshot", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_financial_snapshots_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.ModelParameterSet", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_model_parameter_sets_portfolios_portfolio_id");

                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_model_parameter_sets_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PortfolioPosition", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_positions_portfolios_portfolio_id");

                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_positions_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PortfolioTrade", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_trades_portfolios_portfolio_id");

                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_trades_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.PriceObservation", b =>
                {
                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_price_observations_securities_security_id");
                });

            modelBuilder.Entity("Portwise.Domain.Models.RecommendationSnapshot", b =>
                {
                    b.HasOne("Portwise.Domain.Models.ModelParameterSet", null)
                        .WithMany()
                        .HasForeignKey("ModelParameterSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recommendation_snapshots_model_parameter_set_id");

                    b.HasOne("Portwise.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_snapshots_portfolios_portfolio_id");

                    b.HasOne("Portwise.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_snapshots_securities_security_id");
                });
#pragma warning restore 612, 618
        }
    }
}
