using System.Reflection;
using System.Xml.Linq;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.OpenApi;

namespace Portwise.OpenApi;

/// <summary>
/// Applies XML documentation generated by the API and application assemblies to OpenAPI operations and schemas.
/// </summary>
public sealed class XmlDocumentationOperationTransformer : IOpenApiOperationTransformer
{
    public Task TransformAsync(
        OpenApiOperation operation,
        OpenApiOperationTransformerContext context,
        CancellationToken cancellationToken)
    {
        if (context.Description.ActionDescriptor is ControllerActionDescriptor actionDescriptor)
        {
            var member = XmlDocumentationStore.GetMethodMember(actionDescriptor.MethodInfo);
            if (member is not null)
            {
                operation.Summary = XmlDocumentationStore.ReadText(member.Element("summary"));
                operation.Description = XmlDocumentationStore.ReadText(member.Element("remarks"));
            }
        }

        return Task.CompletedTask;
    }
}

/// <summary>
/// Applies XML documentation to generated OpenAPI schema and property descriptions.
/// </summary>
public sealed class XmlDocumentationSchemaTransformer : IOpenApiSchemaTransformer
{
    public Task TransformAsync(
        OpenApiSchema schema,
        OpenApiSchemaTransformerContext context,
        CancellationToken cancellationToken)
    {
        var type = context.JsonTypeInfo.Type;
        var typeSummary = XmlDocumentationStore.ReadText(
            XmlDocumentationStore.GetTypeMember(type)?.Element("summary"));
        var propertySummary = context.JsonPropertyInfo is null
            ? null
            : XmlDocumentationStore.ReadText(
                XmlDocumentationStore.GetPropertyMember(
                    context.JsonPropertyInfo.DeclaringType ?? type,
                    context.JsonPropertyInfo.Name)?.Element("summary"));
        var summary = propertySummary ?? typeSummary;
        if (!string.IsNullOrWhiteSpace(summary))
        {
            schema.Description = summary;
        }

        return Task.CompletedTask;
    }
}

internal static class XmlDocumentationStore
{
    private static readonly Dictionary<string, XDocument?> Documents = new(StringComparer.OrdinalIgnoreCase);

    public static XElement? GetMethodMember(MethodInfo method)
    {
        var document = GetDocument(method.DeclaringType?.Assembly);
        if (document is null || method.DeclaringType is null)
        {
            return null;
        }

        var declaringTypeName = GetTypeName(method.DeclaringType);
        var prefix = $"M:{declaringTypeName}.{method.Name}";
        return document.Root?.Element("members")?.Elements("member")
            .FirstOrDefault(member => member.Attribute("name")?.Value.StartsWith(prefix, StringComparison.Ordinal) == true);
    }

    public static XElement? GetTypeMember(Type type)
        => GetDocument(type.Assembly)?.Root?.Element("members")?.Elements("member")
            .FirstOrDefault(member => member.Attribute("name")?.Value == $"T:{GetTypeName(type)}");

    public static XElement? GetPropertyMember(Type type, string jsonName)
    {
        var property = type.GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .FirstOrDefault(item => string.Equals(item.Name, jsonName, StringComparison.OrdinalIgnoreCase));
        if (property is null)
        {
            return null;
        }

        return GetDocument(type.Assembly)?.Root?.Element("members")?.Elements("member")
            .FirstOrDefault(member => member.Attribute("name")?.Value == $"P:{GetTypeName(type)}.{property.Name}");
    }

    public static string? ReadText(XElement? element)
        => element is null ? null : string.Join(" ", element.Value.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));

    private static XDocument? GetDocument(Assembly? assembly)
    {
        if (assembly is null)
        {
            return null;
        }

        var key = assembly.FullName ?? assembly.GetName().Name ?? assembly.Location;
        if (Documents.TryGetValue(key, out var cached))
        {
            return cached;
        }

        var path = string.IsNullOrWhiteSpace(assembly.Location)
            ? Path.Combine(
                AppContext.BaseDirectory,
                assembly.GetName().Name + ".xml")
            : Path.ChangeExtension(assembly.Location, ".xml");
        XDocument? document = File.Exists(path) ? XDocument.Load(path, LoadOptions.None) : null;
        Documents[key] = document;
        return document;
    }

    private static string GetTypeName(Type type)
        => (type.FullName ?? type.Name).Replace('+', '.');
}
