<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Riok.Mapperly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Portwise.Domain/Portwise.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="../../locales/**/*.json"
                      Link="Locales/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
