<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="ModelContextProtocol.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../DividendHarvest.Application/DividendHarvest.Application.csproj" />
    <ProjectReference Include="../DividendHarvest.Domain/DividendHarvest.Domain.csproj" />
  </ItemGroup>
</Project>
