/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/budgets/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the current portfolio cash budget summary. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BudgetSummary"];
                        "application/json": components["schemas"]["BudgetSummary"];
                        "text/json": components["schemas"]["BudgetSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Records a cash ledger entry and returns the created entry. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Cash ledger entry details. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordCashLedgerEntryRequest"];
                    "text/json": components["schemas"]["RecordCashLedgerEntryRequest"];
                    "application/*+json": components["schemas"]["RecordCashLedgerEntryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CashLedgerEntryResult"];
                        "application/json": components["schemas"]["CashLedgerEntryResult"];
                        "text/json": components["schemas"]["CashLedgerEntryResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inference/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns all configured inference providers. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InferenceProvidersResponse"];
                        "application/json": components["schemas"]["InferenceProvidersResponse"];
                        "text/json": components["schemas"]["InferenceProvidersResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Creates one OpenAI-compatible inference provider. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Provider name, Base URL, and explicit API key action. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateInferenceProviderRequest"];
                    "text/json": components["schemas"]["CreateInferenceProviderRequest"];
                    "application/*+json": components["schemas"]["CreateInferenceProviderRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InferenceProviderDto"];
                        "application/json": components["schemas"]["InferenceProviderDto"];
                        "text/json": components["schemas"]["InferenceProviderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inference/providers/{providerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Updates one inference provider. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Inference provider identifier. */
                    providerId: string;
                };
                cookie?: never;
            };
            /** @description Provider values, API key action, and expected revision. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateInferenceProviderRequest"];
                    "text/json": components["schemas"]["UpdateInferenceProviderRequest"];
                    "application/*+json": components["schemas"]["UpdateInferenceProviderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InferenceProviderDto"];
                        "application/json": components["schemas"]["InferenceProviderDto"];
                        "text/json": components["schemas"]["InferenceProviderDto"];
                    };
                };
            };
        };
        post?: never;
        /** Deletes an inference provider that is not bound to a route. */
        delete: {
            parameters: {
                query?: {
                    /** @description Revision last read by the caller. */
                    expectedRevision?: number | string;
                };
                header?: never;
                path: {
                    /** @description Inference provider identifier. */
                    providerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inference/providers/{providerId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verifies every complete route bound to one saved provider. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Inference provider identifier. */
                    providerId: string;
                };
                cookie?: never;
            };
            /** @description Expected provider revision. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyInferenceProviderRequest"];
                    "text/json": components["schemas"]["VerifyInferenceProviderRequest"];
                    "application/*+json": components["schemas"]["VerifyInferenceProviderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VerifyInferenceProviderResponse"];
                        "application/json": components["schemas"]["VerifyInferenceProviderResponse"];
                        "text/json": components["schemas"]["VerifyInferenceProviderResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inference/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the Chat and Embedding inference routes. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InferenceRoutesResponse"];
                        "application/json": components["schemas"]["InferenceRoutesResponse"];
                        "text/json": components["schemas"]["InferenceRoutesResponse"];
                    };
                };
            };
        };
        /** Atomically updates the Chat and Embedding inference routes. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Both route bindings and their expected revisions. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateInferenceRoutesRequest"];
                    "text/json": components["schemas"]["UpdateInferenceRoutesRequest"];
                    "application/*+json": components["schemas"]["UpdateInferenceRoutesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InferenceRoutesResponse"];
                        "application/json": components["schemas"]["InferenceRoutesResponse"];
                        "text/json": components["schemas"]["InferenceRoutesResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/initialization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns whether onboarding has been completed and which capabilities are limited. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["InitializationStatusResponse"];
                        "application/json": components["schemas"]["InitializationStatusResponse"];
                        "text/json": components["schemas"]["InitializationStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/initialization/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically saves the first-run preferences and optional provider bindings. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The preferences, portfolio, and optional provider configuration. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteInitializationRequest"];
                    "text/json": components["schemas"]["CompleteInitializationRequest"];
                    "application/*+json": components["schemas"]["CompleteInitializationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompleteInitializationResponse"];
                        "application/json": components["schemas"]["CompleteInitializationResponse"];
                        "text/json": components["schemas"]["CompleteInitializationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Records a simulated portfolio trade. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Trade direction, quantity, price and date. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordPortfolioTradeRequest"];
                    "text/json": components["schemas"]["RecordPortfolioTradeRequest"];
                    "application/*+json": components["schemas"]["RecordPortfolioTradeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PortfolioTradeResult"];
                        "application/json": components["schemas"]["PortfolioTradeResult"];
                        "text/json": components["schemas"]["PortfolioTradeResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the persisted application preferences. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PreferencesResponse"];
                        "application/json": components["schemas"]["PreferencesResponse"];
                        "text/json": components["schemas"]["PreferencesResponse"];
                    };
                };
            };
        };
        /** Updates the application language and theme using optimistic concurrency. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Preference values and the expected revision. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePreferencesRequest"];
                    "text/json": components["schemas"]["UpdatePreferencesRequest"];
                    "application/*+json": components["schemas"]["UpdatePreferencesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PreferencesResponse"];
                        "application/json": components["schemas"]["PreferencesResponse"];
                        "text/json": components["schemas"]["PreferencesResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the current portfolio recommendation. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PortfolioRecommendationResult"];
                        "application/json": components["schemas"]["PortfolioRecommendationResult"];
                        "text/json": components["schemas"]["PortfolioRecommendationResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persists a snapshot of the current recommendation. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateRecommendationSnapshotResult"];
                        "application/json": components["schemas"]["CreateRecommendationSnapshotResult"];
                        "text/json": components["schemas"]["CreateRecommendationSnapshotResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock-data-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns available and configured stock data providers. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockDataProvidersResponse"];
                        "application/json": components["schemas"]["StockDataProvidersResponse"];
                        "text/json": components["schemas"]["StockDataProvidersResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Creates one stock data provider instance. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Provider definition, name, and explicit credential action. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateStockDataProviderRequest"];
                    "text/json": components["schemas"]["CreateStockDataProviderRequest"];
                    "application/*+json": components["schemas"]["CreateStockDataProviderRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockDataProviderDto"];
                        "application/json": components["schemas"]["StockDataProviderDto"];
                        "text/json": components["schemas"]["StockDataProviderDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock-data-providers/{providerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Updates one stock data provider instance. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Stock data provider identifier. */
                    providerId: string;
                };
                cookie?: never;
            };
            /** @description Provider values, credential action, and expected revision. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateStockDataProviderRequest"];
                    "text/json": components["schemas"]["UpdateStockDataProviderRequest"];
                    "application/*+json": components["schemas"]["UpdateStockDataProviderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockDataProviderDto"];
                        "application/json": components["schemas"]["StockDataProviderDto"];
                        "text/json": components["schemas"]["StockDataProviderDto"];
                    };
                };
            };
        };
        post?: never;
        /** Deletes an unbound stock data provider instance. */
        delete: {
            parameters: {
                query?: {
                    /** @description Revision last read by the caller. */
                    expectedRevision?: number | string;
                };
                header?: never;
                path: {
                    /** @description Stock data provider identifier. */
                    providerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock-data-providers/{providerId}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verifies the saved connection without changing its configuration. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Stock data provider identifier. */
                    providerId: string;
                };
                cookie?: never;
            };
            /** @description Expected provider revision. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyStockDataProviderRequest"];
                    "text/json": components["schemas"]["VerifyStockDataProviderRequest"];
                    "application/*+json": components["schemas"]["VerifyStockDataProviderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VerifyStockDataProviderResponse"];
                        "application/json": components["schemas"]["VerifyStockDataProviderResponse"];
                        "text/json": components["schemas"]["VerifyStockDataProviderResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stock-data-providers/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns all fixed stock data capability routes. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockDataRoutesResponse"];
                        "application/json": components["schemas"]["StockDataRoutesResponse"];
                        "text/json": components["schemas"]["StockDataRoutesResponse"];
                    };
                };
            };
        };
        /** Atomically updates all fixed stock data capability routes. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description All route bindings and their expected revisions. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateStockDataRoutesRequest"];
                    "text/json": components["schemas"]["UpdateStockDataRoutesRequest"];
                    "application/*+json": components["schemas"]["UpdateStockDataRoutesRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockDataRoutesResponse"];
                        "application/json": components["schemas"]["StockDataRoutesResponse"];
                        "text/json": components["schemas"]["StockDataRoutesResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns all stocks configured in the portfolio watchlist. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockWatchlistItem"][];
                        "application/json": components["schemas"]["StockWatchlistItem"][];
                        "text/json": components["schemas"]["StockWatchlistItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs a manual synchronization for all configured stocks. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockDataSyncRunResult"];
                        "application/json": components["schemas"]["StockDataSyncRunResult"];
                        "text/json": components["schemas"]["StockDataSyncRunResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{securityCode}/{exchangeCode}/model-parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the active model parameters for one stock. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Six-digit A-share security code. */
                    securityCode: string;
                    /** @description Exchange code: SSE, SZSE or BSE. */
                    exchangeCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockModelParameterSet"];
                        "application/json": components["schemas"]["StockModelParameterSet"];
                        "text/json": components["schemas"]["StockModelParameterSet"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/model-parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a new model-parameter version for one stock. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Model parameter values and effective date. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveStockModelParametersRequest"];
                    "text/json": components["schemas"]["SaveStockModelParametersRequest"];
                    "application/*+json": components["schemas"]["SaveStockModelParametersRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockModelParameterSet"];
                        "application/json": components["schemas"]["StockModelParameterSet"];
                        "text/json": components["schemas"]["StockModelParameterSet"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{securityCode}/{exchangeCode}/price-observations/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synchronizes the latest price observation for one stock. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Six-digit A-share security code. */
                    securityCode: string;
                    /** @description Exchange code: SSE, SZSE or BSE. */
                    exchangeCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockPriceObservationResult"];
                        "application/json": components["schemas"]["StockPriceObservationResult"];
                        "text/json": components["schemas"]["StockPriceObservationResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{securityCode}/{exchangeCode}/dividend-events/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synchronizes dividend events for one stock. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Six-digit A-share security code. */
                    securityCode: string;
                    /** @description Exchange code: SSE, SZSE or BSE. */
                    exchangeCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockDividendEventResult"][];
                        "application/json": components["schemas"]["StockDividendEventResult"][];
                        "text/json": components["schemas"]["StockDividendEventResult"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{securityCode}/{exchangeCode}/financial-snapshots/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synchronizes financial snapshots for one stock. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Six-digit A-share security code. */
                    securityCode: string;
                    /** @description Exchange code: SSE, SZSE or BSE. */
                    exchangeCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockFinancialSnapshotResult"][];
                        "application/json": components["schemas"]["StockFinancialSnapshotResult"][];
                        "text/json": components["schemas"]["StockFinancialSnapshotResult"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{securityCode}/{exchangeCode}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the current recommendation analysis for one stock. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Six-digit A-share security code. */
                    securityCode: string;
                    /** @description Exchange code: SSE, SZSE or BSE. */
                    exchangeCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockRecommendationResult"];
                        "application/json": components["schemas"]["StockRecommendationResult"];
                        "text/json": components["schemas"]["StockRecommendationResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Returns the persisted application language and theme codes. */
        ApplicationPreferenceDto: {
            languageCode: string;
            themeCode: string;
            /** Format: int64 */
            revision: number | string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        /** @description Aggregated cash budget information for the configured portfolio. */
        BudgetSummary: {
            /**
             * Format: uuid
             * @description Identifier of the portfolio.
             */
            portfolioId: string;
            /** @description Display name of the portfolio. */
            portfolioName: string;
            /**
             * Format: double
             * @description Total cash inflow recorded to date.
             */
            totalInflowAmount: number | string;
            /**
             * Format: double
             * @description Total cash outflow recorded to date.
             */
            totalOutflowAmount: number | string;
            /**
             * Format: double
             * @description Current cash balance.
             */
            cashBalanceAmount: number | string;
            /**
             * Format: int32
             * @description Number of ledger entries included in the calculation.
             */
            entryCount: number | string;
            /**
             * Format: date-time
             * @description UTC timestamp when the summary was computed.
             */
            computedAt: string;
        };
        /** @description Describes one capability that is unavailable or not fully configured. */
        CapabilityLimitationDto: {
            capabilityCode: string;
            statusCode: string;
        };
        /** @description Result returned after a cash ledger entry is recorded. */
        CashLedgerEntryResult: {
            /**
             * Format: uuid
             * @description Identifier of the created cash ledger entry.
             */
            cashLedgerEntryId: string;
            /**
             * Format: uuid
             * @description Identifier of the portfolio.
             */
            portfolioId: string;
            /**
             * Format: date
             * @description Date of the ledger entry.
             */
            entryDate: string;
            /** @description Normalized ledger entry type code. */
            entryTypeCode: string;
            /** @description Normalized cash direction code. */
            cashDirectionCode: string;
            /**
             * Format: double
             * @description Cash amount recorded.
             */
            cashAmount: number | string;
            /** @description Optional security code associated with the entry. */
            securityCode: null | string;
            /** @description Optional exchange code associated with the entry. */
            exchangeCode: null | string;
            /** @description Optional source-system record identifier. */
            sourceRecordId: null | string;
        };
        /** @description Describes an optional inference provider to save during onboarding. */
        CompleteInferenceProviderRequest: {
            name: string;
            baseUrl: string;
            apiKey: components["schemas"]["SecretUpdateRequest"];
        };
        /** @description Describes an optional Chat or Embedding binding by provider name and model. */
        CompleteInferenceRouteRequest: {
            capabilityCode: string;
            providerName: null | string;
            modelName: null | string;
        };
        /** @description Supplies preferences, the unique portfolio, and optional external capabilities. */
        CompleteInitializationRequest: {
            languageCode: string;
            themeCode: string;
            portfolioName: string;
            stockDataProviders: null | components["schemas"]["CompleteStockDataProviderRequest"][];
            stockDataRoutes: null | components["schemas"]["CompleteStockDataRouteRequest"][];
            inferenceProviders: null | components["schemas"]["CompleteInferenceProviderRequest"][];
            inferenceRoutes: null | components["schemas"]["CompleteInferenceRouteRequest"][];
        };
        /** @description Returns the persisted readiness and limitation state after onboarding. */
        CompleteInitializationResponse: {
            status: components["schemas"]["InitializationStatusResponse"];
        };
        /** @description Describes an optional stock data provider to save during onboarding. */
        CompleteStockDataProviderRequest: {
            /** Format: uuid */
            providerDefinitionId: string;
            name: string;
            credentials: components["schemas"]["SecretUpdateRequest"];
        };
        /** @description Describes an optional stock data capability binding by provider name. */
        CompleteStockDataRouteRequest: {
            capabilityCode: string;
            providerName: null | string;
        };
        /** @description Requests creation of one OpenAI-compatible inference provider. */
        CreateInferenceProviderRequest: {
            name: string;
            baseUrl: string;
            apiKey: components["schemas"]["SecretUpdateRequest"];
        };
        /** @description Result of persisting a portfolio recommendation snapshot. */
        CreateRecommendationSnapshotResult: {
            /**
             * Format: uuid
             * @description Identifier of the model run.
             */
            modelRunId: string;
            /**
             * Format: uuid
             * @description Identifier of the portfolio.
             */
            portfolioId: string;
            /**
             * Format: int32
             * @description Number of stock snapshots persisted.
             */
            snapshotCount: number | string;
            /**
             * Format: date-time
             * @description UTC timestamp when the recommendation was computed.
             */
            computedAt: string;
            /** @description Persisted stock recommendation snapshots. */
            stocks: components["schemas"]["StockRecommendationResult"][];
        };
        /** @description Requests creation of one stock data provider instance. */
        CreateStockDataProviderRequest: {
            /** Format: uuid */
            providerDefinitionId: string;
            name: string;
            credentials: components["schemas"]["SecretUpdateRequest"];
        };
        /** @description Describes one inference provider without returning its API key. */
        InferenceProviderDto: {
            /** Format: uuid */
            id: string;
            name: string;
            providerTypeCode: string;
            baseUrl: string;
            secretState: components["schemas"]["SecretStateDto"];
            runtimeStatusCode: string;
            verificationStateCode: string;
            /** Format: date-time */
            lastVerifiedAtUtc: null | string;
            lastVerificationErrorCode: null | string;
            /** Format: int64 */
            revision: number | string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        /** @description Returns all configured inference providers. */
        InferenceProvidersResponse: {
            providers: components["schemas"]["InferenceProviderDto"][];
        };
        /** @description Describes one inference capability binding and its effective runtime status. */
        InferenceRouteDto: {
            /** Format: uuid */
            id: string;
            capabilityCode: string;
            /** Format: uuid */
            providerId: null | string;
            modelName: null | string;
            runtimeStatusCode: string;
            /** Format: int64 */
            revision: number | string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        /** @description Returns the fixed Chat and Embedding inference routes. */
        InferenceRoutesResponse: {
            routes: components["schemas"]["InferenceRouteDto"][];
        };
        /** @description Returns entry readiness, saved preferences, and independent capability limitations. */
        InitializationStatusResponse: {
            isComplete: boolean;
            /** Format: date-time */
            completedAtUtc: null | string;
            preferences: null | components["schemas"]["ApplicationPreferenceDto"];
            limitations: components["schemas"]["CapabilityLimitationDto"][];
        };
        /** @description Portfolio-level recommendation and budget allocation result. */
        PortfolioRecommendationResult: {
            /**
             * Format: uuid
             * @description Identifier of the portfolio.
             */
            portfolioId: string;
            /**
             * Format: double
             * @description Available budget before allocation.
             */
            startingAvailableBudgetAmount: number | string;
            /**
             * Format: double
             * @description Available budget after allocation.
             */
            remainingAvailableBudgetAmount: number | string;
            /**
             * Format: double
             * @description Total suggested trade amount.
             */
            totalSuggestedTradeAmount: number | string;
            /**
             * Format: double
             * @description Estimated fees for suggested trades.
             */
            estimatedTransactionFeeAmount: number | string;
            /** @description Per-stock recommendation results. */
            stocks: components["schemas"]["StockRecommendationResult"][];
            /**
             * Format: date-time
             * @description UTC timestamp when the recommendation was computed.
             */
            computedAt: string;
        };
        /** @description Result returned after a portfolio trade is recorded. */
        PortfolioTradeResult: {
            /**
             * Format: uuid
             * @description Identifier of the created trade.
             */
            portfolioTradeId: string;
            /**
             * Format: uuid
             * @description Identifier of the portfolio.
             */
            portfolioId: string;
            /** @description Traded security code. */
            securityCode: string;
            /** @description Traded exchange code. */
            exchangeCode: string;
            /**
             * Format: date
             * @description Trade execution date.
             */
            tradeDate: string;
            /** @description Normalized trade direction code. */
            tradeDirectionCode: string;
            /**
             * Format: int32
             * @description Number of shares traded.
             */
            shareQuantity: number | string;
            /**
             * Format: double
             * @description Execution price per share.
             */
            pricePerShare: number | string;
            /**
             * Format: double
             * @description Transaction fee charged.
             */
            transactionFeeAmount: number | string;
            /**
             * Format: int32
             * @description Shares held after the trade.
             */
            heldShares: number | string;
            /**
             * Format: int32
             * @description Core shares after the trade.
             */
            coreShares: number | string;
            /**
             * Format: int32
             * @description Target shares after the trade.
             */
            targetShares: number | string;
            /**
             * Format: double
             * @description Average cost per share after the trade.
             */
            averageCostPerShare: number | string;
            /**
             * Format: double
             * @description Trade principal amount.
             */
            tradePrincipalAmount: number | string;
        };
        /** @description Returns the persisted application language and theme. */
        PreferencesResponse: {
            /** @description Stable application language code. */
            languageCode: string;
            /** @description Stable application theme code. */
            themeCode: string;
            /**
             * Format: int64
             * @description Current optimistic concurrency revision.
             */
            revision: number | string;
            /**
             * Format: date-time
             * @description Time at which the preferences were last updated.
             */
            updatedAtUtc: string;
        };
        /** @description Request to record a cash ledger entry. */
        RecordCashLedgerEntryRequest: {
            /**
             * Format: date
             * @description Date of the ledger entry.
             */
            entryDate: string;
            /** @description Ledger entry type code. */
            entryTypeCode: string;
            /** @description Cash direction code. */
            cashDirectionCode: string;
            /**
             * Format: double
             * @description Cash amount to record.
             */
            cashAmount: number | string;
            /** @description Optional security code associated with the entry. */
            securityCode: null | string;
            /** @description Optional exchange code associated with the entry. */
            exchangeCode: null | string;
            /** @description Optional source-system record identifier. */
            sourceRecordId: null | string;
        };
        /** @description Request to record a simulated portfolio trade. */
        RecordPortfolioTradeRequest: {
            /** @description Security code to trade. */
            securityCode: string;
            /** @description Exchange code for the security. */
            exchangeCode: string;
            /**
             * Format: date
             * @description Trade execution date.
             */
            tradeDate: string;
            /** @description Trade direction code. */
            tradeDirectionCode: string;
            /**
             * Format: int32
             * @description Number of shares to trade.
             */
            shareQuantity: number | string;
            /**
             * Format: double
             * @description Execution price per share.
             */
            pricePerShare: number | string;
            /**
             * Format: double
             * @description Transaction fee amount.
             */
            transactionFeeAmount: number | string;
            /** @description Optional source-system record identifier. */
            sourceRecordId: null | string;
        };
        /** @description Request to create a versioned model-parameter set for one stock. */
        SaveStockModelParametersRequest: {
            /** @description Six-digit security code. */
            securityCode: string;
            /** @description Exchange code. */
            exchangeCode: string;
            /** @description Client-defined model version label. */
            modelVersion: string;
            /**
             * Format: double
             * @description Yield threshold for strong-buy recommendations.
             */
            strongBuyYieldThreshold: number | string;
            /**
             * Format: double
             * @description Yield threshold for accumulation recommendations.
             */
            accumulationYieldThreshold: number | string;
            /**
             * Format: double
             * @description Yield threshold for partial-trim recommendations.
             */
            partialTrimYieldThreshold: number | string;
            /**
             * Format: double
             * @description Yield threshold for aggressive-trim recommendations.
             */
            aggressiveTrimYieldThreshold: number | string;
            /**
             * Format: double
             * @description Budget ratio for strong-buy recommendations.
             */
            strongBuyBudgetRatio: number | string;
            /**
             * Format: double
             * @description Budget ratio for accumulation recommendations.
             */
            accumulateBudgetRatio: number | string;
            /**
             * Format: double
             * @description Position ratio for partial trims.
             */
            partialTrimRatio: number | string;
            /**
             * Format: double
             * @description Position ratio for aggressive trims.
             */
            aggressiveTrimRatio: number | string;
            /**
             * Format: double
             * @description Maximum security portfolio weight.
             */
            maxSecurityWeight: number | string;
            /**
             * Format: double
             * @description Maximum sector portfolio weight.
             */
            maxSectorWeight: number | string;
            /**
             * Format: double
             * @description Portfolio cash reserve ratio.
             */
            cashReserveRatio: number | string;
            /**
             * Format: double
             * @description Maximum amount for one trade.
             */
            maxSingleTradeAmount: number | string;
            /**
             * Format: double
             * @description Maximum budget for one period.
             */
            maxPeriodBudgetAmount: number | string;
            /**
             * Format: double
             * @description Transaction fee ratio.
             */
            transactionFeeRatio: number | string;
            /**
             * Format: double
             * @description Minimum transaction fee amount.
             */
            minimumTransactionFeeAmount: number | string;
            /**
             * Format: int32
             * @description Trading lot size in shares.
             */
            tradingLotSize: number | string;
            /**
             * Format: date
             * @description Date from which the parameters apply.
             */
            effectiveFromDate: string;
        };
        /** @description Describes whether a saved secret is missing, configured, or unreadable. */
        SecretStateDto: {
            /** @description Stable secret state code. */
            stateCode: string;
        };
        /** @description Requests an explicit keep, replace, or clear operation for a secret. */
        SecretUpdateRequest: {
            /** @description Stable secret update action code. */
            action: string;
            /** @description New plaintext only when the action is replace. */
            value: null | string;
        };
        /** @description Current market, dividend, position and recommendation analysis for one stock. */
        StockAnalysisResult: {
            /** @description Security code. */
            securityCode: string;
            /** @description Exchange code. */
            exchangeCode: string;
            /** @description Display name of the security. */
            securityName: string;
            /** @description Model availability status code. */
            modelStatusCode: string;
            /** @description Dividend reliability status code. */
            dividendReliabilityCode: string;
            /**
             * Format: double
             * @description Latest valid close price.
             */
            closePrice: null | number | string;
            /**
             * Format: double
             * @description Model dividend per share.
             */
            modelDividendPerShare: null | number | string;
            /** @description Dividend mode code, when available. */
            dividendModeCode: null | string;
            /**
             * Format: double
             * @description Latest model dividend yield.
             */
            dividendYield: null | number | string;
            /**
             * Format: double
             * @description Strong-buy price threshold.
             */
            strongBuyPrice: null | number | string;
            /**
             * Format: double
             * @description Accumulation price threshold.
             */
            accumulatePrice: null | number | string;
            /**
             * Format: double
             * @description Partial-trim price threshold.
             */
            partialTrimPrice: null | number | string;
            /**
             * Format: double
             * @description Aggressive-trim price threshold.
             */
            aggressiveTrimPrice: null | number | string;
            /** @description Latest observed price-zone code. */
            observedPriceZoneCode: null | string;
            /** @description Confirmed price-zone code. */
            priceZoneCode: null | string;
            /** @description Whether the price zone is confirmed. */
            priceZoneConfirmed: boolean;
            /** @description Recommendation code. */
            recommendationCode: string;
            /**
             * Format: int32
             * @description Current held shares.
             */
            heldShares: number | string;
            /**
             * Format: int32
             * @description Current core shares.
             */
            coreShares: number | string;
            /**
             * Format: int32
             * @description Current satellite shares.
             */
            satelliteShares: number | string;
            /**
             * Format: date
             * @description Date through which source data is valid.
             */
            dataAsOfDate: null | string;
            /**
             * Format: uuid
             * @description Identifier of the applied parameter set.
             */
            modelParameterSetId: null | string;
            /**
             * Format: date-time
             * @description UTC timestamp when the analysis was computed.
             */
            computedAt: string;
            /** @description Stable explanation code emitted by the domain. */
            explanation: string;
            /**
             * Format: uuid
             * @description Persistent identifier of the security.
             */
            securityId: string;
        };
        /** @description Describes an available migration-managed stock data provider kind. */
        StockDataProviderDefinitionDto: {
            /** Format: uuid */
            id: string;
            providerKindCode: string;
            displayName: string;
            isEnabled: boolean;
        };
        /** @description Describes one configured stock data provider without returning its credentials. */
        StockDataProviderDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            providerDefinitionId: string;
            providerKindCode: string;
            name: string;
            secretState: components["schemas"]["SecretStateDto"];
            runtimeStatusCode: string;
            verificationStateCode: string;
            /** Format: date-time */
            lastVerifiedAtUtc: null | string;
            lastVerificationErrorCode: null | string;
            /** Format: int64 */
            revision: number | string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        /** @description Returns available provider definitions and configured provider instances. */
        StockDataProvidersResponse: {
            definitions: components["schemas"]["StockDataProviderDefinitionDto"][];
            providers: components["schemas"]["StockDataProviderDto"][];
        };
        /** @description Describes the provider binding and effective status for one stock data capability. */
        StockDataRouteDto: {
            /** Format: uuid */
            id: string;
            capabilityCode: string;
            /** Format: uuid */
            providerId: null | string;
            runtimeStatusCode: string;
            /** Format: int64 */
            revision: number | string;
            /** Format: date-time */
            updatedAtUtc: string;
        };
        /** @description Returns all fixed stock data capability routes. */
        StockDataRoutesResponse: {
            routes: components["schemas"]["StockDataRouteDto"][];
        };
        /** @description Describes one stock data synchronization failure. */
        StockDataSyncFailure: {
            /** @description Security code that failed. */
            securityCode: string;
            /** @description Exchange code that failed. */
            exchangeCode: string;
            /** @description Kind of data that failed to synchronize. */
            dataKind: string;
            /** @description Stable failure code. */
            errorCode: string;
            /** @description Structured failure parameters. */
            parameters: Record<string, never>;
        };
        /** @description Summary of a stock data synchronization run. */
        StockDataSyncRunResult: {
            /**
             * Format: int32
             * @description Number of stocks attempted.
             */
            attemptedStockCount: number | string;
            /**
             * Format: int32
             * @description Number of fully synchronized stocks.
             */
            fullyCompletedStockCount: number | string;
            /**
             * Format: int32
             * @description Number of stocks with partial failures.
             */
            partiallyFailedStockCount: number | string;
            /** @description Failures collected during synchronization. */
            failures: components["schemas"]["StockDataSyncFailure"][];
            /**
             * Format: date-time
             * @description UTC completion timestamp.
             */
            completedAt: string;
        };
        /** @description Persisted dividend event returned by the API. */
        StockDividendEventResult: {
            /**
             * Format: uuid
             * @description Identifier of the persisted dividend event.
             */
            dividendEventId: string;
            /** @description Security code. */
            securityCode: string;
            /** @description Exchange code. */
            exchangeCode: string;
            /**
             * Format: double
             * @description Dividend amount per share.
             */
            dividendPerShare: number | string;
            /** @description Normalized dividend type code. */
            dividendTypeCode: string;
            /** @description Normalized dividend status code. */
            dividendStatusCode: string;
            /**
             * Format: date
             * @description Announcement date, when available.
             */
            announcementDate: null | string;
            /**
             * Format: date
             * @description Ex-dividend date, when available.
             */
            exDividendDate: null | string;
            /**
             * Format: date
             * @description Payment date, when available.
             */
            paymentDate: null | string;
            /** @description Whether the dividend is special. */
            isSpecialDividend: boolean;
            /**
             * Format: date-time
             * @description Publication timestamp, when available.
             */
            publishedAt: null | string;
            /**
             * Format: date-time
             * @description UTC capture timestamp.
             */
            capturedAt: string;
            /** @description Source-system name. */
            dataSource: string;
            /** @description Source-system record identifier. */
            sourceRecordId: string;
            /** @description Normalized data quality code. */
            dataQualityCode: string;
        };
        /** @description Persisted financial snapshot returned by the API. */
        StockFinancialSnapshotResult: {
            /**
             * Format: uuid
             * @description Identifier of the persisted financial snapshot.
             */
            financialSnapshotId: string;
            /** @description Security code. */
            securityCode: string;
            /** @description Exchange code. */
            exchangeCode: string;
            /**
             * Format: date
             * @description Date through which the data is valid.
             */
            dataAsOfDate: string;
            /**
             * Format: date-time
             * @description UTC capture timestamp.
             */
            capturedAt: string;
            /**
             * Format: date-time
             * @description Publication timestamp, when available.
             */
            publishedAt: null | string;
            /**
             * Format: double
             * @description Earnings per share, when available.
             */
            earningsPerShare: null | number | string;
            /**
             * Format: double
             * @description Dividend payout ratio, when available.
             */
            dividendPayoutRatio: null | number | string;
            /**
             * Format: double
             * @description Three-year average payout ratio.
             */
            threeYearAverageDividendPayoutRatio: null | number | string;
            /**
             * Format: double
             * @description Price-to-book ratio, when available.
             */
            priceToBookRatio: null | number | string;
            /**
             * Format: double
             * @description Return on equity, when available.
             */
            returnOnEquity: null | number | string;
            /** @description Source-system name. */
            dataSource: string;
            /** @description Source-system record identifier. */
            sourceRecordId: string;
            /** @description Normalized data quality code. */
            dataQualityCode: string;
        };
        /** @description Snapshot of the shares held for one configured stock. */
        StockHoldingSnapshot: {
            /**
             * Format: int32
             * @description Total shares currently held.
             */
            heldShares: number | string;
            /**
             * Format: int32
             * @description Shares assigned to the core position.
             */
            coreShares: number | string;
            /**
             * Format: int32
             * @description Desired target share quantity.
             */
            targetShares: number | string;
            /**
             * Format: double
             * @description Average acquisition cost per share.
             */
            averageCostPerShare: number | string;
        };
        /** @description Effective model parameters for one configured stock. */
        StockModelParameterSet: {
            /**
             * Format: uuid
             * @description Identifier of the parameter set.
             */
            modelParameterSetId: string;
            /** @description Security code. */
            securityCode: string;
            /** @description Exchange code. */
            exchangeCode: string;
            /** @description Model version label. */
            modelVersion: string;
            /**
             * Format: double
             * @description Yield threshold for strong-buy recommendations.
             */
            strongBuyYieldThreshold: number | string;
            /**
             * Format: double
             * @description Yield threshold for accumulation recommendations.
             */
            accumulationYieldThreshold: number | string;
            /**
             * Format: double
             * @description Yield threshold for partial-trim recommendations.
             */
            partialTrimYieldThreshold: number | string;
            /**
             * Format: double
             * @description Yield threshold for aggressive-trim recommendations.
             */
            aggressiveTrimYieldThreshold: number | string;
            /**
             * Format: double
             * @description Budget ratio for strong-buy recommendations.
             */
            strongBuyBudgetRatio: number | string;
            /**
             * Format: double
             * @description Budget ratio for accumulation recommendations.
             */
            accumulateBudgetRatio: number | string;
            /**
             * Format: double
             * @description Position ratio for partial trims.
             */
            partialTrimRatio: number | string;
            /**
             * Format: double
             * @description Position ratio for aggressive trims.
             */
            aggressiveTrimRatio: number | string;
            /**
             * Format: double
             * @description Maximum security portfolio weight.
             */
            maxSecurityWeight: number | string;
            /**
             * Format: double
             * @description Maximum sector portfolio weight.
             */
            maxSectorWeight: number | string;
            /**
             * Format: double
             * @description Portfolio cash reserve ratio.
             */
            cashReserveRatio: number | string;
            /**
             * Format: double
             * @description Maximum amount for one trade.
             */
            maxSingleTradeAmount: number | string;
            /**
             * Format: double
             * @description Maximum budget for one period.
             */
            maxPeriodBudgetAmount: number | string;
            /**
             * Format: double
             * @description Transaction fee ratio.
             */
            transactionFeeRatio: number | string;
            /**
             * Format: double
             * @description Minimum transaction fee amount.
             */
            minimumTransactionFeeAmount: number | string;
            /**
             * Format: int32
             * @description Trading lot size in shares.
             */
            tradingLotSize: number | string;
            /**
             * Format: date
             * @description Date from which the parameters apply.
             */
            effectiveFromDate: string;
        };
        /** @description Persisted price observation returned by the API. */
        StockPriceObservationResult: {
            /**
             * Format: uuid
             * @description Identifier of the persisted observation.
             */
            priceObservationId: string;
            /** @description Security code. */
            securityCode: string;
            /** @description Exchange code. */
            exchangeCode: string;
            /**
             * Format: date
             * @description Trading date.
             */
            tradingDate: string;
            /**
             * Format: double
             * @description Closing price.
             */
            closePrice: number | string;
            /**
             * Format: date-time
             * @description UTC observation timestamp.
             */
            priceObservedAt: string;
            /** @description Source-system name. */
            dataSource: string;
            /** @description Source-system record identifier. */
            sourceRecordId: string;
            /** @description Normalized data quality code. */
            dataQualityCode: string;
        };
        /** @description Recommendation and suggested trade quantities for one stock. */
        StockRecommendationResult: {
            /** @description Underlying stock analysis. */
            analysis: components["schemas"]["StockAnalysisResult"];
            /**
             * Format: int32
             * @description Suggested buy quantity in shares.
             */
            suggestedBuyShares: number | string;
            /**
             * Format: int32
             * @description Suggested sell quantity in shares.
             */
            suggestedSellShares: number | string;
            /**
             * Format: double
             * @description Suggested trade amount.
             */
            suggestedTradeAmount: number | string;
            /**
             * Format: double
             * @description Estimated transaction fee.
             */
            estimatedTransactionFeeAmount: number | string;
        };
        /** @description Configured stock identity with its latest holding snapshot. */
        StockWatchlistItem: {
            /** @description Security code. */
            securityCode: string;
            /** @description Exchange code. */
            exchangeCode: string;
            /** @description Display name of the security. */
            securityName: string;
            /** @description Normalized market code. */
            marketCode: string;
            /** @description Normalized currency code. */
            currencyCode: string;
            holding: null | components["schemas"]["StockHoldingSnapshot"];
            /** @description Optional normalized sector code. */
            sectorCode?: null | string;
            /**
             * Format: uuid
             * @description Persistent identifier of the configured security.
             */
            securityId?: string;
        };
        /** @description Requests an optimistic-concurrency update to one inference provider. */
        UpdateInferenceProviderRequest: {
            name: string;
            baseUrl: string;
            apiKey: components["schemas"]["SecretUpdateRequest"];
            /** Format: int64 */
            expectedRevision: number | string;
        };
        /** @description Requests one inference route binding update. */
        UpdateInferenceRouteRequest: {
            capabilityCode: string;
            /** Format: uuid */
            providerId: null | string;
            modelName: null | string;
            /** Format: int64 */
            expectedRevision: number | string;
        };
        /** @description Requests one atomic update to both inference capability routes. */
        UpdateInferenceRoutesRequest: {
            routes: components["schemas"]["UpdateInferenceRouteRequest"][];
        };
        /** @description Requests an optimistic-concurrency update to application preferences. */
        UpdatePreferencesRequest: {
            /** @description Stable application language code. */
            languageCode: string;
            /** @description Stable application theme code. */
            themeCode: string;
            /**
             * Format: int64
             * @description Revision last read by the caller.
             */
            expectedRevision: number | string;
        };
        /** @description Requests an optimistic-concurrency update to a stock data provider. */
        UpdateStockDataProviderRequest: {
            name: string;
            credentials: components["schemas"]["SecretUpdateRequest"];
            /** Format: int64 */
            expectedRevision: number | string;
        };
        /** @description Requests one optimistic-concurrency stock data route binding update. */
        UpdateStockDataRouteRequest: {
            capabilityCode: string;
            /** Format: uuid */
            providerId: null | string;
            /** Format: int64 */
            expectedRevision: number | string;
        };
        /** @description Requests one atomic update to all fixed stock data capability routes. */
        UpdateStockDataRoutesRequest: {
            routes: components["schemas"]["UpdateStockDataRouteRequest"][];
        };
        /** @description Requests connection verification for the last observed provider revision. */
        VerifyInferenceProviderRequest: {
            /** Format: int64 */
            expectedRevision: number | string;
        };
        /** @description Returns the provider state recorded after a connection verification attempt. */
        VerifyInferenceProviderResponse: {
            provider: components["schemas"]["InferenceProviderDto"];
        };
        /** @description Requests connection verification for the last observed provider revision. */
        VerifyStockDataProviderRequest: {
            /** Format: int64 */
            expectedRevision: number | string;
        };
        /** @description Returns the provider state recorded after a connection verification attempt. */
        VerifyStockDataProviderResponse: {
            provider: components["schemas"]["StockDataProviderDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
