/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/budgets/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BudgetSummary"];
                        "application/json": components["schemas"]["BudgetSummary"];
                        "text/json": components["schemas"]["BudgetSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/budgets/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordCashLedgerEntryRequest"];
                    "text/json": components["schemas"]["RecordCashLedgerEntryRequest"];
                    "application/*+json": components["schemas"]["RecordCashLedgerEntryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CashLedgerEntryResult"];
                        "application/json": components["schemas"]["CashLedgerEntryResult"];
                        "text/json": components["schemas"]["CashLedgerEntryResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RecordPortfolioTradeRequest"];
                    "text/json": components["schemas"]["RecordPortfolioTradeRequest"];
                    "application/*+json": components["schemas"]["RecordPortfolioTradeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PortfolioTradeResult"];
                        "application/json": components["schemas"]["PortfolioTradeResult"];
                        "text/json": components["schemas"]["PortfolioTradeResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PortfolioRecommendationResult"];
                        "application/json": components["schemas"]["PortfolioRecommendationResult"];
                        "text/json": components["schemas"]["PortfolioRecommendationResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateRecommendationSnapshotResult"];
                        "application/json": components["schemas"]["CreateRecommendationSnapshotResult"];
                        "text/json": components["schemas"]["CreateRecommendationSnapshotResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SetupStatus"];
                        "application/json": components["schemas"]["SetupStatus"];
                        "text/json": components["schemas"]["SetupStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetupRequest"];
                    "text/json": components["schemas"]["SetupRequest"];
                    "application/*+json": components["schemas"]["SetupRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SetupResult"];
                        "application/json": components["schemas"]["SetupResult"];
                        "text/json": components["schemas"]["SetupResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockWatchlistItem"][];
                        "application/json": components["schemas"]["StockWatchlistItem"][];
                        "text/json": components["schemas"]["StockWatchlistItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockDataSyncRunResult"];
                        "application/json": components["schemas"]["StockDataSyncRunResult"];
                        "text/json": components["schemas"]["StockDataSyncRunResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{securityCode}/{exchangeCode}/model-parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    securityCode: string;
                    exchangeCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockModelParameterSet"];
                        "application/json": components["schemas"]["StockModelParameterSet"];
                        "text/json": components["schemas"]["StockModelParameterSet"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/model-parameters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveStockModelParametersRequest"];
                    "text/json": components["schemas"]["SaveStockModelParametersRequest"];
                    "application/*+json": components["schemas"]["SaveStockModelParametersRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockModelParameterSet"];
                        "application/json": components["schemas"]["StockModelParameterSet"];
                        "text/json": components["schemas"]["StockModelParameterSet"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{securityCode}/{exchangeCode}/price-observations/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    securityCode: string;
                    exchangeCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockPriceObservationResult"];
                        "application/json": components["schemas"]["StockPriceObservationResult"];
                        "text/json": components["schemas"]["StockPriceObservationResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{securityCode}/{exchangeCode}/dividend-events/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    securityCode: string;
                    exchangeCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockDividendEventResult"][];
                        "application/json": components["schemas"]["StockDividendEventResult"][];
                        "text/json": components["schemas"]["StockDividendEventResult"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{securityCode}/{exchangeCode}/financial-snapshots/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    securityCode: string;
                    exchangeCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockFinancialSnapshotResult"][];
                        "application/json": components["schemas"]["StockFinancialSnapshotResult"][];
                        "text/json": components["schemas"]["StockFinancialSnapshotResult"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{securityCode}/{exchangeCode}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    securityCode: string;
                    exchangeCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["StockRecommendationResult"];
                        "application/json": components["schemas"]["StockRecommendationResult"];
                        "text/json": components["schemas"]["StockRecommendationResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BudgetSummary: {
            /** Format: uuid */
            portfolioId: string;
            portfolioName: string;
            /** Format: double */
            totalInflowAmount: number | string;
            /** Format: double */
            totalOutflowAmount: number | string;
            /** Format: double */
            cashBalanceAmount: number | string;
            /** Format: int32 */
            entryCount: number | string;
            /** Format: date-time */
            computedAt: string;
        };
        CashLedgerEntryResult: {
            /** Format: uuid */
            cashLedgerEntryId: string;
            /** Format: uuid */
            portfolioId: string;
            /** Format: date */
            entryDate: string;
            entryTypeCode: string;
            cashDirectionCode: string;
            /** Format: double */
            cashAmount: number | string;
            securityCode: null | string;
            exchangeCode: null | string;
            sourceRecordId: null | string;
        };
        CreateRecommendationSnapshotResult: {
            /** Format: uuid */
            modelRunId: string;
            /** Format: uuid */
            portfolioId: string;
            /** Format: int32 */
            snapshotCount: number | string;
            /** Format: date-time */
            computedAt: string;
            stocks: components["schemas"]["StockRecommendationResult"][];
        };
        InitialHoldingInput: {
            /** Format: int32 */
            heldShares: number | string;
            /** Format: int32 */
            coreShares: number | string;
            /** Format: int32 */
            targetShares: number | string;
            /** Format: double */
            averageCostPerShare: number | string;
        };
        PortfolioRecommendationResult: {
            /** Format: uuid */
            portfolioId: string;
            /** Format: double */
            startingAvailableBudgetAmount: number | string;
            /** Format: double */
            remainingAvailableBudgetAmount: number | string;
            /** Format: double */
            totalSuggestedTradeAmount: number | string;
            /** Format: double */
            estimatedTransactionFeeAmount: number | string;
            stocks: components["schemas"]["StockRecommendationResult"][];
            /** Format: date-time */
            computedAt: string;
        };
        PortfolioTradeResult: {
            /** Format: uuid */
            portfolioTradeId: string;
            /** Format: uuid */
            portfolioId: string;
            securityCode: string;
            exchangeCode: string;
            /** Format: date */
            tradeDate: string;
            tradeDirectionCode: string;
            /** Format: int32 */
            shareQuantity: number | string;
            /** Format: double */
            pricePerShare: number | string;
            /** Format: double */
            transactionFeeAmount: number | string;
            /** Format: int32 */
            heldShares: number | string;
            /** Format: int32 */
            coreShares: number | string;
            /** Format: int32 */
            targetShares: number | string;
            /** Format: double */
            averageCostPerShare: number | string;
            /** Format: double */
            tradePrincipalAmount: number | string;
        };
        RecordCashLedgerEntryRequest: {
            /** Format: date */
            entryDate: string;
            entryTypeCode: string;
            cashDirectionCode: string;
            /** Format: double */
            cashAmount: number | string;
            securityCode: null | string;
            exchangeCode: null | string;
            sourceRecordId: null | string;
        };
        RecordPortfolioTradeRequest: {
            securityCode: string;
            exchangeCode: string;
            /** Format: date */
            tradeDate: string;
            tradeDirectionCode: string;
            /** Format: int32 */
            shareQuantity: number | string;
            /** Format: double */
            pricePerShare: number | string;
            /** Format: double */
            transactionFeeAmount: number | string;
            sourceRecordId: null | string;
        };
        SaveStockModelParametersRequest: {
            securityCode: string;
            exchangeCode: string;
            modelVersion: string;
            /** Format: double */
            strongBuyYieldThreshold: number | string;
            /** Format: double */
            accumulationYieldThreshold: number | string;
            /** Format: double */
            partialTrimYieldThreshold: number | string;
            /** Format: double */
            aggressiveTrimYieldThreshold: number | string;
            /** Format: double */
            strongBuyBudgetRatio: number | string;
            /** Format: double */
            accumulateBudgetRatio: number | string;
            /** Format: double */
            partialTrimRatio: number | string;
            /** Format: double */
            aggressiveTrimRatio: number | string;
            /** Format: double */
            maxSecurityWeight: number | string;
            /** Format: double */
            maxSectorWeight: number | string;
            /** Format: double */
            cashReserveRatio: number | string;
            /** Format: double */
            maxSingleTradeAmount: number | string;
            /** Format: double */
            maxPeriodBudgetAmount: number | string;
            /** Format: double */
            transactionFeeRatio: number | string;
            /** Format: double */
            minimumTransactionFeeAmount: number | string;
            /** Format: int32 */
            tradingLotSize: number | string;
            /** Format: date */
            effectiveFromDate: string;
        };
        SetupRequest: {
            portfolioName: string;
            stocks: components["schemas"]["SetupStockRequest"][];
        };
        SetupResult: {
            /** Format: uuid */
            portfolioId: string;
            portfolioName: string;
            stockDataSyncScheduled: boolean;
            stocks: components["schemas"]["SetupStockResult"][];
        };
        SetupStatus: {
            isComplete: boolean;
            missingRequirements: string[];
        };
        SetupStockRequest: {
            securityCode: string;
            exchangeCode: string;
            initialHolding: null | components["schemas"]["InitialHoldingInput"];
        };
        SetupStockResult: {
            securityCode: string;
            exchangeCode: string;
            securityName: null | string;
        };
        StockAnalysisResult: {
            securityCode: string;
            exchangeCode: string;
            securityName: string;
            modelStatusCode: string;
            dividendReliabilityCode: string;
            /** Format: double */
            closePrice: null | number | string;
            /** Format: double */
            modelDividendPerShare: null | number | string;
            dividendModeCode: null | string;
            /** Format: double */
            dividendYield: null | number | string;
            /** Format: double */
            strongBuyPrice: null | number | string;
            /** Format: double */
            accumulatePrice: null | number | string;
            /** Format: double */
            partialTrimPrice: null | number | string;
            /** Format: double */
            aggressiveTrimPrice: null | number | string;
            observedPriceZoneCode: null | string;
            priceZoneCode: null | string;
            priceZoneConfirmed: boolean;
            recommendationCode: string;
            /** Format: int32 */
            heldShares: number | string;
            /** Format: int32 */
            coreShares: number | string;
            /** Format: int32 */
            satelliteShares: number | string;
            /** Format: date */
            dataAsOfDate: null | string;
            /** Format: uuid */
            modelParameterSetId: null | string;
            /** Format: date-time */
            computedAt: string;
            explanation: string;
            /** Format: uuid */
            securityId: string;
        };
        StockDataSyncFailure: {
            securityCode: string;
            exchangeCode: string;
            dataKind: string;
            errorCode: string;
            parameters: Record<string, never>;
        };
        StockDataSyncRunResult: {
            /** Format: int32 */
            attemptedStockCount: number | string;
            /** Format: int32 */
            fullyCompletedStockCount: number | string;
            /** Format: int32 */
            partiallyFailedStockCount: number | string;
            failures: components["schemas"]["StockDataSyncFailure"][];
            /** Format: date-time */
            completedAt: string;
        };
        StockDividendEventResult: {
            /** Format: uuid */
            dividendEventId: string;
            securityCode: string;
            exchangeCode: string;
            /** Format: double */
            dividendPerShare: number | string;
            dividendTypeCode: string;
            dividendStatusCode: string;
            /** Format: date */
            announcementDate: null | string;
            /** Format: date */
            exDividendDate: null | string;
            /** Format: date */
            paymentDate: null | string;
            isSpecialDividend: boolean;
            /** Format: date-time */
            publishedAt: null | string;
            /** Format: date-time */
            capturedAt: string;
            dataSource: string;
            sourceRecordId: string;
            dataQualityCode: string;
        };
        StockFinancialSnapshotResult: {
            /** Format: uuid */
            financialSnapshotId: string;
            securityCode: string;
            exchangeCode: string;
            /** Format: date */
            dataAsOfDate: string;
            /** Format: date-time */
            capturedAt: string;
            /** Format: date-time */
            publishedAt: null | string;
            /** Format: double */
            earningsPerShare: null | number | string;
            /** Format: double */
            dividendPayoutRatio: null | number | string;
            /** Format: double */
            threeYearAverageDividendPayoutRatio: null | number | string;
            /** Format: double */
            priceToBookRatio: null | number | string;
            /** Format: double */
            returnOnEquity: null | number | string;
            dataSource: string;
            sourceRecordId: string;
            dataQualityCode: string;
        };
        StockHoldingSnapshot: {
            /** Format: int32 */
            heldShares: number | string;
            /** Format: int32 */
            coreShares: number | string;
            /** Format: int32 */
            targetShares: number | string;
            /** Format: double */
            averageCostPerShare: number | string;
        };
        StockModelParameterSet: {
            /** Format: uuid */
            modelParameterSetId: string;
            securityCode: string;
            exchangeCode: string;
            modelVersion: string;
            /** Format: double */
            strongBuyYieldThreshold: number | string;
            /** Format: double */
            accumulationYieldThreshold: number | string;
            /** Format: double */
            partialTrimYieldThreshold: number | string;
            /** Format: double */
            aggressiveTrimYieldThreshold: number | string;
            /** Format: double */
            strongBuyBudgetRatio: number | string;
            /** Format: double */
            accumulateBudgetRatio: number | string;
            /** Format: double */
            partialTrimRatio: number | string;
            /** Format: double */
            aggressiveTrimRatio: number | string;
            /** Format: double */
            maxSecurityWeight: number | string;
            /** Format: double */
            maxSectorWeight: number | string;
            /** Format: double */
            cashReserveRatio: number | string;
            /** Format: double */
            maxSingleTradeAmount: number | string;
            /** Format: double */
            maxPeriodBudgetAmount: number | string;
            /** Format: double */
            transactionFeeRatio: number | string;
            /** Format: double */
            minimumTransactionFeeAmount: number | string;
            /** Format: int32 */
            tradingLotSize: number | string;
            /** Format: date */
            effectiveFromDate: string;
        };
        StockPriceObservationResult: {
            /** Format: uuid */
            priceObservationId: string;
            securityCode: string;
            exchangeCode: string;
            /** Format: date */
            tradingDate: string;
            /** Format: double */
            closePrice: number | string;
            /** Format: date-time */
            priceObservedAt: string;
            dataSource: string;
            sourceRecordId: string;
            dataQualityCode: string;
        };
        StockRecommendationResult: {
            analysis: components["schemas"]["StockAnalysisResult"];
            /** Format: int32 */
            suggestedBuyShares: number | string;
            /** Format: int32 */
            suggestedSellShares: number | string;
            /** Format: double */
            suggestedTradeAmount: number | string;
            /** Format: double */
            estimatedTransactionFeeAmount: number | string;
        };
        StockWatchlistItem: {
            securityCode: string;
            exchangeCode: string;
            securityName: string;
            marketCode: string;
            currencyCode: string;
            holding: null | components["schemas"]["StockHoldingSnapshot"];
            sectorCode?: null | string;
            /** Format: uuid */
            securityId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
