// <auto-generated />
using System;
using DividendHarvest.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DividendHarvest.Infrastructure.Migrations
{
    [DbContext(typeof(DividendHarvestDbContext))]
    [Migration("20260907225950_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("DividendHarvest.Domain.Models.CashLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_ledger_entry_id");

                    b.Property<decimal>("CashAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_amount");

                    b.Property<string>("CashDirectionCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_direction_code");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_date");

                    b.Property<string>("EntryTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_type_code");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid?>("SecurityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_record_id");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId");

                    b.HasIndex("PortfolioId", "SourceRecordId")
                        .IsUnique()
                        .HasFilter("source_record_id IS NOT NULL");

                    b.ToTable("cash_ledger_entries", (string)null);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.DividendEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_event_id");

                    b.Property<DateOnly?>("AnnouncementDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("announcement_date");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at");

                    b.Property<string>("DataQualityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_quality_code");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_source");

                    b.Property<decimal>("DividendPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_per_share");

                    b.Property<string>("DividendStatusCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_status_code");

                    b.Property<string>("DividendTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_type_code");

                    b.Property<DateOnly?>("ExDividendDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ex_dividend_date");

                    b.Property<bool>("IsSpecialDividend")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_special_dividend");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_record_id");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId", "SourceRecordId")
                        .IsUnique();

                    b.ToTable("dividend_events", (string)null);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.FinancialSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("financial_snapshot_id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("captured_at");

                    b.Property<DateOnly>("DataAsOfDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_as_of_date");

                    b.Property<string>("DataQualityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_quality_code");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_source");

                    b.Property<decimal?>("DividendPayoutRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_payout_ratio");

                    b.Property<decimal?>("EarningsPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("earnings_per_share");

                    b.Property<decimal?>("PriceToBookRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("price_to_book_ratio");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at");

                    b.Property<decimal?>("ReturnOnEquity")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("return_on_equity");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_record_id");

                    b.Property<decimal?>("ThreeYearAverageDividendPayoutRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("three_year_average_dividend_payout_ratio");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId", "DataAsOfDate")
                        .IsUnique();

                    b.ToTable("financial_snapshots", (string)null);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.ModelParameterSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("model_parameter_set_id");

                    b.Property<decimal>("AccumulateBudgetRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("accumulate_budget_ratio");

                    b.Property<decimal>("AccumulationYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("accumulation_yield_threshold");

                    b.Property<decimal>("AggressiveTrimRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("aggressive_trim_ratio");

                    b.Property<decimal>("AggressiveTrimYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("aggressive_trim_yield_threshold");

                    b.Property<decimal>("CashReserveRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("cash_reserve_ratio");

                    b.Property<DateOnly>("EffectiveFromDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_from_date");

                    b.Property<decimal>("MaxPeriodBudgetAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("max_period_budget_amount");

                    b.Property<decimal>("MaxSectorWeight")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("max_sector_weight");

                    b.Property<decimal>("MaxSecurityWeight")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("max_security_weight");

                    b.Property<decimal>("MaxSingleTradeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("max_single_trade_amount");

                    b.Property<decimal>("MinimumTransactionFeeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("minimum_transaction_fee_amount");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_version");

                    b.Property<decimal>("PartialTrimRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("partial_trim_ratio");

                    b.Property<decimal>("PartialTrimYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("partial_trim_yield_threshold");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_id");

                    b.Property<decimal>("StrongBuyBudgetRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("strong_buy_budget_ratio");

                    b.Property<decimal>("StrongBuyYieldThreshold")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("strong_buy_yield_threshold");

                    b.Property<int>("TradingLotSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("trading_lot_size");

                    b.Property<decimal>("TransactionFeeRatio")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_fee_ratio");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId");

                    b.HasIndex("PortfolioId", "SecurityId", "EffectiveFromDate")
                        .IsUnique();

                    b.ToTable("model_parameter_sets", (string)null);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_name");

                    b.HasKey("Id");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.PortfolioPosition", b =>
                {
                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_id");

                    b.Property<decimal>("AverageCostPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("average_cost_per_share");

                    b.Property<int>("CoreShares")
                        .HasColumnType("INTEGER")
                        .HasColumnName("core_shares");

                    b.Property<int>("HeldShares")
                        .HasColumnType("INTEGER")
                        .HasColumnName("held_shares");

                    b.Property<int>("TargetShares")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_shares");

                    b.HasKey("PortfolioId", "SecurityId");

                    b.HasIndex("SecurityId");

                    b.ToTable("portfolio_positions", (string)null);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.PortfolioTrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_trade_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("PricePerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_share");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_id");

                    b.Property<int>("ShareQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("share_quantity");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_record_id");

                    b.Property<DateOnly>("TradeDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("trade_date");

                    b.Property<string>("TradeDirectionCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("trade_direction_code");

                    b.Property<decimal>("TransactionFeeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("transaction_fee_amount");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId");

                    b.HasIndex("PortfolioId", "SourceRecordId")
                        .IsUnique();

                    b.HasIndex("PortfolioId", "TradeDate");

                    b.ToTable("portfolio_trades", (string)null);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.PriceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("price_observation_id");

                    b.Property<decimal>("ClosePrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("close_price");

                    b.Property<string>("DataQualityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_quality_code");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("data_source");

                    b.Property<DateTimeOffset>("PriceObservedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_observed_at");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_record_id");

                    b.Property<DateOnly>("TradingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("trading_date");

                    b.HasKey("Id");

                    b.HasIndex("SecurityId", "TradingDate")
                        .IsUnique();

                    b.ToTable("price_observations", (string)null);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.RecommendationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("recommendation_snapshot_id");

                    b.Property<decimal?>("ClosePrice")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("close_price");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("computed_at");

                    b.Property<DateOnly?>("DataAsOfDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_as_of_date");

                    b.Property<string>("DividendModeCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_mode_code");

                    b.Property<string>("DividendReliabilityCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_reliability_code");

                    b.Property<decimal?>("DividendYield")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("dividend_yield");

                    b.Property<decimal>("EstimatedTransactionFeeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("estimated_transaction_fee_amount");

                    b.Property<decimal?>("ModelDividendPerShare")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_dividend_per_share");

                    b.Property<Guid?>("ModelParameterSetId")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_parameter_set_id");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("model_run_id");

                    b.Property<string>("ModelStatusCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("model_status_code");

                    b.Property<string>("ObservedPriceZoneCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("observed_price_zone_code");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT")
                        .HasColumnName("portfolio_id");

                    b.Property<string>("PriceZoneCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("price_zone_code");

                    b.Property<bool>("PriceZoneConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("price_zone_confirmed");

                    b.Property<string>("RecommendationCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("recommendation_code");

                    b.Property<Guid>("SecurityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("security_id");

                    b.Property<int>("SuggestedBuyShares")
                        .HasColumnType("INTEGER")
                        .HasColumnName("suggested_buy_shares");

                    b.Property<int>("SuggestedSellShares")
                        .HasColumnType("INTEGER")
                        .HasColumnName("suggested_sell_shares");

                    b.Property<decimal>("SuggestedTradeAmount")
                        .HasPrecision(20, 8)
                        .HasColumnType("TEXT")
                        .HasColumnName("suggested_trade_amount");

                    b.HasKey("Id");

                    b.HasIndex("ModelParameterSetId");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("SecurityId");

                    b.HasIndex("ModelRunId", "PortfolioId", "SecurityId")
                        .IsUnique();

                    b.ToTable("recommendation_snapshots", (string)null);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.Security", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("security_id");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency_code");

                    b.Property<string>("ExchangeCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("exchange_code");

                    b.Property<string>("MarketCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("market_code");

                    b.Property<string>("SectorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("sector_code");

                    b.Property<string>("SecurityCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_code");

                    b.Property<string>("SecurityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_name");

                    b.HasKey("Id");

                    b.HasIndex("ExchangeCode", "SecurityCode")
                        .IsUnique();

                    b.ToTable("securities", (string)null);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.CashLedgerEntry", b =>
                {
                    b.HasOne("DividendHarvest.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DividendHarvest.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.DividendEvent", b =>
                {
                    b.HasOne("DividendHarvest.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.FinancialSnapshot", b =>
                {
                    b.HasOne("DividendHarvest.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.ModelParameterSet", b =>
                {
                    b.HasOne("DividendHarvest.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DividendHarvest.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.PortfolioPosition", b =>
                {
                    b.HasOne("DividendHarvest.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DividendHarvest.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.PortfolioTrade", b =>
                {
                    b.HasOne("DividendHarvest.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DividendHarvest.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.PriceObservation", b =>
                {
                    b.HasOne("DividendHarvest.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DividendHarvest.Domain.Models.RecommendationSnapshot", b =>
                {
                    b.HasOne("DividendHarvest.Domain.Models.ModelParameterSet", null)
                        .WithMany()
                        .HasForeignKey("ModelParameterSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DividendHarvest.Domain.Models.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DividendHarvest.Domain.Models.Security", null)
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
